import { EffectInputCallbackError, invokeEffectInput } from "@effect-ui/core";
import type { EffectInput } from "@effect-ui/core";
import { Data, Effect } from "effect";
import type { CollectionPersistenceStorage } from "./collection-contract.js";

/** Default SQLite table used by collection persistence helpers. */
export const SQLITE_PERSISTENCE_DEFAULT_TABLE = "effect_ui_collection_persistence";
/** Default namespace prefix for persisted collection snapshot rows. */
export const SQLITE_PERSISTENCE_DEFAULT_NAMESPACE = "effect-ui:collections";
/** Default schema version written to collection persistence rows. */
export const SQLITE_PERSISTENCE_DEFAULT_SCHEMA_VERSION = 1;

/**
 * Namespaced key for one persisted collection snapshot.
 */
export interface SQLitePersistenceKey {
  readonly namespace: string;
  readonly key: string;
}

/**
 * Row shape stored by the SQLite persistence driver.
 */
export interface SQLitePersistenceRow extends SQLitePersistenceKey {
  readonly schemaVersion: number;
  readonly value: string;
  readonly updatedAt: number;
}

/**
 * Effect-aware table adapter for persistence rows.
 *
 * Implement this directly for custom SQLite clients, or use
 * `makeSQLiteStatementPersistenceDriver` for SQL statement based clients.
 */
export interface SQLitePersistenceTable<E = never, R = never> {
  readonly ensure?: () => EffectInput<void, E, R>;
  readonly get: (key: SQLitePersistenceKey) => EffectInput<SQLitePersistenceRow | null, E, R>;
  readonly upsert: (row: SQLitePersistenceRow) => EffectInput<void, E, R>;
  readonly delete?: (key: SQLitePersistenceKey) => EffectInput<void, E, R>;
}

/**
 * Driver that resolves named persistence tables.
 */
export interface SQLitePersistenceDriver<E = never, R = never> {
  readonly table: (name: string) => SQLitePersistenceTable<E, R>;
}

/**
 * SQLite parameter value supported by generated persistence SQL.
 */
export type SQLiteStatementValue = string | number | null;

/** Positional parameter list accepted by generated SQLite persistence SQL. */
export type SQLiteStatementParams = ReadonlyArray<SQLiteStatementValue>;

/**
 * Row shape returned by generated SELECT statements.
 */
export interface SQLiteStatementRow {
  readonly namespace?: unknown;
  readonly key?: unknown;
  readonly schema_version?: unknown;
  readonly schemaVersion?: unknown;
  readonly value?: unknown;
  readonly updated_at?: unknown;
  readonly updatedAt?: unknown;
}

/**
 * Minimal SQL statement database used by the SQLite persistence driver.
 */
export interface SQLiteStatementDatabase<E = never, R = never> {
  readonly execute: (sql: string, params?: SQLiteStatementParams) => EffectInput<void, E, R>;
  readonly select: (sql: string, params?: SQLiteStatementParams) => EffectInput<ReadonlyArray<SQLiteStatementRow>, E, R>;
}

/**
 * Prepared statement shape for clients with `run` and `all` methods.
 */
export interface SQLitePreparedStatement<
  Row extends SQLiteStatementRow = SQLiteStatementRow,
  E = never,
  R = never
> {
  readonly run: (...params: Array<SQLiteStatementValue>) => EffectInput<void, E, R>;
  readonly all: (...params: Array<SQLiteStatementValue>) => EffectInput<ReadonlyArray<Row>, E, R>;
}

/**
 * SQLite client shape for adapters that expose `prepare`.
 */
export interface SQLitePreparedStatementDatabase<
  Row extends SQLiteStatementRow = SQLiteStatementRow,
  E = never,
  R = never
> {
  readonly prepare: (sql: string) => EffectInput<SQLitePreparedStatement<Row, E, R>, E, R>;
}

/**
 * Options for the prepared-statement adapter.
 */
export interface SQLitePreparedStatementDatabaseOptions {
  readonly cache?: boolean;
}

/**
 * SQL statement recorded by the in-memory statement database.
 */
export interface SQLiteMemoryStatement {
  readonly sql: string;
  readonly params?: SQLiteStatementParams;
}

/**
 * In-memory implementation of the generated persistence SQL.
 *
 * Useful for tests and examples. It records statements and supports only the
 * SQL generated by `makeSQLiteStatementPersistenceDriver`.
 */
export interface SQLiteMemoryStatementDatabase extends SQLiteStatementDatabase<never, never> {
  readonly statements: ReadonlyArray<SQLiteMemoryStatement>;
  row(table: string, namespace: string, key: string): SQLitePersistenceRow | undefined;
  tableRows(table: string): ReadonlyArray<SQLitePersistenceRow>;
  clear(): void;
}

/**
 * Options for collection persistence stored in SQLite.
 */
export interface SQLitePersistenceOptions {
  readonly namespace?: string;
  readonly tableName?: string;
  readonly schemaVersion?: number;
  readonly now?: () => number;
}

/**
 * Error raised before generating SQL for an invalid table name.
 */
export class SQLitePersistenceInvalidTableName extends Data.TaggedError(
  "SQLitePersistenceInvalidTableName"
)<{
  readonly tableName: string;
  readonly reason: "Empty" | "ContainsNul";
  readonly guidance: string;
}> {}

/**
 * Error raised by the in-memory adapter for SQL outside the generated subset.
 */
export class SQLitePersistenceUnsupportedStatement extends Data.TaggedError(
  "SQLitePersistenceUnsupportedStatement"
)<{
  readonly sql: string;
  readonly operation: "tableName" | "execute" | "select";
  readonly guidance: string;
}> {}

/** Error raised when a SQLite statement row does not match the persistence row contract. */
export class SQLitePersistenceInvalidRow extends Data.TaggedError(
  "SQLitePersistenceInvalidRow"
)<{
  readonly field: "namespace" | "key" | "schema_version" | "value" | "updated_at";
  readonly value: unknown;
  readonly expected: "string" | "finite-number";
  readonly guidance: string;
}> {}

/** Error raised when generated in-memory SQLite statements receive malformed params. */
export class SQLitePersistenceInvalidStatementParams extends Data.TaggedError(
  "SQLitePersistenceInvalidStatementParams"
)<{
  readonly operation: "insert" | "select" | "delete";
  readonly field: "params" | "namespace" | "key" | "schema_version" | "value" | "updated_at";
  readonly value: unknown;
  readonly expected: "exact-param-count" | "string" | "finite-number";
  readonly expectedCount?: number;
  readonly actualCount?: number;
  readonly guidance: string;
}> {}

const runCallback = <A, E, R>(
  operation: string,
  callback: () => EffectInput<A, E, R>
): Effect.Effect<A, E | EffectInputCallbackError, R> =>
  invokeEffectInput(`SQLitePersistence.${operation}`, callback);

const quoteIdentifier = (identifier: string): string => {
  if (identifier.length === 0 || identifier.includes("\0")) {
    throw new SQLitePersistenceInvalidTableName({
      tableName: identifier,
      reason: identifier.length === 0 ? "Empty" : "ContainsNul",
      guidance: "Use a non-empty SQLite table name that does not contain NUL bytes."
    });
  }

  return `"${identifier.replaceAll("\"", "\"\"")}"`;
};

const unquoteIdentifier = (identifier: string): string =>
  identifier.startsWith("\"") && identifier.endsWith("\"")
    ? identifier.slice(1, -1).replaceAll("\"\"", "\"")
    : identifier;

const sqlTableName = (sql: string): string => {
  const match =
    sql.match(/\bINTO\s+("[^"]*(?:""[^"]*)*")/i) ??
    sql.match(/\bFROM\s+("[^"]*(?:""[^"]*)*")/i) ??
    sql.match(/\bEXISTS\s+("[^"]*(?:""[^"]*)*")/i);
  if (!match?.[1]) {
    throw new SQLitePersistenceUnsupportedStatement({
      sql,
      operation: "tableName",
      guidance: "Use SQL generated by makeSQLiteStatementPersistenceDriver or extend the memory adapter parser."
    });
  }
  return unquoteIdentifier(match[1]);
};

const invalidStatementRow = (
  field: SQLitePersistenceInvalidRow["field"],
  value: unknown,
  expected: SQLitePersistenceInvalidRow["expected"]
): SQLitePersistenceInvalidRow =>
  new SQLitePersistenceInvalidRow({
    field,
    value,
    expected,
    guidance: "SQLite statement adapters must return persisted rows with exact string fields and finite numeric timestamp/version fields."
  });

const statementRowNumber = (
  field: SQLitePersistenceInvalidRow["field"],
  value: unknown
): Effect.Effect<number, SQLitePersistenceInvalidRow> =>
  typeof value === "number" && Number.isFinite(value)
    ? Effect.succeed(value)
    : Effect.fail(invalidStatementRow(field, value, "finite-number"));

const statementRowString = (
  field: SQLitePersistenceInvalidRow["field"],
  value: unknown
): Effect.Effect<string, SQLitePersistenceInvalidRow> =>
  typeof value === "string"
    ? Effect.succeed(value)
    : Effect.fail(invalidStatementRow(field, value, "string"));

const sqlitePersistenceRowEffect = (
  row: SQLitePersistenceRow
): Effect.Effect<SQLitePersistenceRow, SQLitePersistenceInvalidRow> =>
  Effect.gen(function* () {
    return {
      namespace: yield* statementRowString("namespace", row.namespace),
      key: yield* statementRowString("key", row.key),
      schemaVersion: yield* statementRowNumber("schema_version", row.schemaVersion),
      value: yield* statementRowString("value", row.value),
      updatedAt: yield* statementRowNumber("updated_at", row.updatedAt)
    };
  });

const invalidStatementParams = (
  operation: SQLitePersistenceInvalidStatementParams["operation"],
  field: SQLitePersistenceInvalidStatementParams["field"],
  value: unknown,
  expected: SQLitePersistenceInvalidStatementParams["expected"],
  counts: Pick<SQLitePersistenceInvalidStatementParams, "expectedCount" | "actualCount"> = {}
): SQLitePersistenceInvalidStatementParams =>
  new SQLitePersistenceInvalidStatementParams({
    operation,
    field,
    value,
    expected,
    ...counts,
    guidance: "The in-memory SQLite adapter supports generated statements with exact params: string namespace/key/value fields and finite numeric schema_version/updated_at fields."
  });

const statementParams = (
  operation: SQLitePersistenceInvalidStatementParams["operation"],
  params: SQLiteStatementParams | undefined,
  expectedCount: number
): ReadonlyArray<unknown> => {
  const values = params === undefined ? [] : Array.isArray(params) ? params : undefined;
  if (values === undefined || values.length !== expectedCount) {
    throw invalidStatementParams(operation, "params", params, "exact-param-count", {
      expectedCount,
      ...(values === undefined ? {} : { actualCount: values.length })
    });
  }
  return values;
};

const statementParamNumber = (
  operation: SQLitePersistenceInvalidStatementParams["operation"],
  field: Extract<SQLitePersistenceInvalidStatementParams["field"], "schema_version" | "updated_at">,
  value: unknown
): number => {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }
  throw invalidStatementParams(operation, field, value, "finite-number");
};

const statementParamString = (
  operation: SQLitePersistenceInvalidStatementParams["operation"],
  field: Extract<SQLitePersistenceInvalidStatementParams["field"], "namespace" | "key" | "value">,
  value: unknown
): string => {
  if (typeof value === "string") {
    return value;
  }
  throw invalidStatementParams(operation, field, value, "string");
};

const statementParamList = (params?: SQLiteStatementParams): Array<SQLiteStatementValue> =>
  params === undefined ? [] : [...params];

const memoryRowId = (table: string, key: SQLitePersistenceKey): string =>
  `${table}\0${key.namespace}\0${key.key}`;

/**
 * Create an in-memory statement database that understands generated SQL.
 *
 * Use for tests or demos that need SQLite persistence behavior without a real
 * SQLite runtime.
 */
export const makeSQLiteMemoryStatementDatabase = (): SQLiteMemoryStatementDatabase => {
  const rows = new Map<string, SQLitePersistenceRow>();
  const statements: Array<SQLiteMemoryStatement> = [];

  const row = (table: string, namespace: string, key: string): SQLitePersistenceRow | undefined =>
    rows.get(memoryRowId(table, { namespace, key }));

  const tableRows = (table: string): ReadonlyArray<SQLitePersistenceRow> =>
    Array.from(rows.entries())
      .filter(([id]) => id.startsWith(`${table}\0`))
      .map(([, value]) => ({ ...value }));

  return {
    statements,
    execute: (sql, params) => {
      statements.push(params === undefined ? { sql } : { sql, params });
      if (/^\s*CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\b/i.test(sql)) {
        void sqlTableName(sql);
        return;
      }

      if (/^\s*INSERT\s+INTO\b/i.test(sql)) {
        const table = sqlTableName(sql);
        const insertParams = statementParams("insert", params, 5);
        const namespace = statementParamString("insert", "namespace", insertParams[0]);
        const key = statementParamString("insert", "key", insertParams[1]);
        const schemaVersion = statementParamNumber("insert", "schema_version", insertParams[2]);
        const value = statementParamString("insert", "value", insertParams[3]);
        const updatedAt = statementParamNumber("insert", "updated_at", insertParams[4]);
        rows.set(memoryRowId(table, { namespace, key }), {
          namespace,
          key,
          schemaVersion,
          value,
          updatedAt
        });
        return;
      }

      if (/^\s*DELETE\s+FROM\b/i.test(sql)) {
        const table = sqlTableName(sql);
        const deleteParams = statementParams("delete", params, 2);
        rows.delete(memoryRowId(table, {
          namespace: statementParamString("delete", "namespace", deleteParams[0]),
          key: statementParamString("delete", "key", deleteParams[1])
        }));
        return;
      }

      throw new SQLitePersistenceUnsupportedStatement({
        sql,
        operation: "execute",
        guidance: "The in-memory SQLite adapter supports generated CREATE, INSERT, and DELETE statements only."
      });
    },
    select: (sql, params) => {
      statements.push(params === undefined ? { sql } : { sql, params });
      if (!/^\s*SELECT\b/i.test(sql)) {
        throw new SQLitePersistenceUnsupportedStatement({
          sql,
          operation: "select",
          guidance: "The in-memory SQLite adapter supports generated SELECT statements only."
        });
      }

      const table = sqlTableName(sql);
      const selectParams = statementParams("select", params, 2);
      const current = row(
        table,
        statementParamString("select", "namespace", selectParams[0]),
        statementParamString("select", "key", selectParams[1])
      );
      return current
        ? [{
            namespace: current.namespace,
            key: current.key,
            schema_version: current.schemaVersion,
            value: current.value,
            updated_at: current.updatedAt
          }]
        : [];
    },
    row,
    tableRows,
    clear: () => {
      rows.clear();
      statements.length = 0;
    }
  };
};

/**
 * Adapt a `prepare`/`run`/`all` SQLite client to the statement database shape.
 *
 * Enable `cache` to reuse prepared statements by SQL string.
 */
export const makeSQLitePreparedStatementDatabase = <
  Row extends SQLiteStatementRow = SQLiteStatementRow,
  E = never,
  R = never
>(
  database: SQLitePreparedStatementDatabase<Row, E, R>,
  options: SQLitePreparedStatementDatabaseOptions = {}
): SQLiteStatementDatabase<E | EffectInputCallbackError, R> => {
  const cache = options.cache === true
    ? new Map<string, SQLitePreparedStatement<Row, E, R>>()
    : undefined;

  const prepare = (sql: string): Effect.Effect<SQLitePreparedStatement<Row, E, R>, E | EffectInputCallbackError, R> =>
    Effect.gen(function* () {
      const cached = cache?.get(sql);
      if (cached) {
        return cached;
      }

      const statement = yield* runCallback("prepare", () => database.prepare(sql));
      cache?.set(sql, statement);
      return statement;
    });

  return {
    execute: (sql, params): Effect.Effect<void, E | EffectInputCallbackError, R> =>
      Effect.flatMap(prepare(sql), (statement) =>
        Effect.asVoid(runCallback("run", () => statement.run(...statementParamList(params))))
      ),
    select: (sql, params): Effect.Effect<ReadonlyArray<SQLiteStatementRow>, E | EffectInputCallbackError, R> =>
      Effect.flatMap(prepare(sql), (statement) =>
        runCallback("all", () => statement.all(...statementParamList(params)))
      )
  };
};

/**
 * Build a persistence driver from a simple SQL statement database.
 *
 * The driver creates the table if needed, stores snapshots by namespace/key,
 * and quotes table names defensively.
 */
export const makeSQLiteStatementPersistenceDriver = <E = never, R = never>(
  database: SQLiteStatementDatabase<E, R>
): SQLitePersistenceDriver<E | EffectInputCallbackError | SQLitePersistenceInvalidRow, R> => ({
  table: (name) => {
    const table = quoteIdentifier(name);
    return {
      ensure: () =>
        runCallback("execute", () => database.execute(
          `CREATE TABLE IF NOT EXISTS ${table} (` +
            "\"namespace\" TEXT NOT NULL, " +
            "\"key\" TEXT NOT NULL, " +
            "\"schema_version\" INTEGER NOT NULL, " +
            "\"value\" TEXT NOT NULL, " +
            "\"updated_at\" INTEGER NOT NULL, " +
            "PRIMARY KEY (\"namespace\", \"key\")" +
          ")"
        )),
      get: (key) =>
        Effect.gen(function* () {
          const rows = yield* runCallback("select", () => database.select(
            `SELECT "namespace", "key", "schema_version", "value", "updated_at" FROM ${table} ` +
              "WHERE \"namespace\" = ? AND \"key\" = ? LIMIT 1",
            [key.namespace, key.key]
          ));
          const row = rows[0];
          if (!row) {
            return null;
          }

          return {
            namespace: yield* statementRowString("namespace", row.namespace),
            key: yield* statementRowString("key", row.key),
            schemaVersion: yield* statementRowNumber("schema_version", row.schemaVersion ?? row.schema_version),
            value: yield* statementRowString("value", row.value),
            updatedAt: yield* statementRowNumber("updated_at", row.updatedAt ?? row.updated_at)
          } satisfies SQLitePersistenceRow;
        }),
      upsert: (row) =>
        runCallback("execute", () => database.execute(
          `INSERT INTO ${table} ("namespace", "key", "schema_version", "value", "updated_at") ` +
            "VALUES (?, ?, ?, ?, ?) " +
            "ON CONFLICT(\"namespace\", \"key\") DO UPDATE SET " +
            "\"schema_version\" = excluded.\"schema_version\", " +
            "\"value\" = excluded.\"value\", " +
            "\"updated_at\" = excluded.\"updated_at\"",
          [row.namespace, row.key, row.schemaVersion, row.value, row.updatedAt]
        )),
      delete: (key) =>
        runCallback("execute", () => database.execute(
          `DELETE FROM ${table} WHERE "namespace" = ? AND "key" = ?`,
          [key.namespace, key.key]
        ))
    };
  }
});

/**
 * Create `CollectionPersistenceStorage` backed by SQLite.
 *
 * Schema-version mismatches read as `null`, letting callers fall back to a
 * fresh load. Database errors and services flow through the returned storage
 * error and requirement channels.
 *
 * @example
 * const storage = makeSQLitePersistenceStorage(
 *   makeSQLiteStatementPersistenceDriver(database)
 * )
 */
export const makeSQLitePersistenceStorage = <E = never, R = never>(
  driver: SQLitePersistenceDriver<E, R>,
  options: SQLitePersistenceOptions = {}
): CollectionPersistenceStorage<E | EffectInputCallbackError | SQLitePersistenceInvalidRow | SQLitePersistenceInvalidTableName, R> => {
  const namespace = options.namespace ?? SQLITE_PERSISTENCE_DEFAULT_NAMESPACE;
  const tableName = options.tableName ?? SQLITE_PERSISTENCE_DEFAULT_TABLE;
  const schemaVersion = options.schemaVersion ?? SQLITE_PERSISTENCE_DEFAULT_SCHEMA_VERSION;
  const now = (): number =>
    options.now === undefined ? Date.now() : options.now();

  const tableEffect = (): Effect.Effect<
    SQLitePersistenceTable<E, R>,
    EffectInputCallbackError | SQLitePersistenceInvalidTableName
  > =>
    Effect.try({
      try: () => driver.table(tableName),
      catch: (cause) =>
        cause instanceof SQLitePersistenceInvalidTableName
          ? cause
          : new EffectInputCallbackError({
              operation: "SQLitePersistence.table",
              cause,
              guidance: "SQLite persistence drivers must synchronously return a table adapter. Effectful work belongs in table ensure/get/upsert/delete callbacks."
            })
    });

  const runStorageCallback = <A>(
    operation: string,
    callback: () => EffectInput<A, E, R>
  ): Effect.Effect<A, E | EffectInputCallbackError, R> =>
    runCallback(operation, callback);

  const ensureTable = (
    table: SQLitePersistenceTable<E, R>
  ): Effect.Effect<void, E | EffectInputCallbackError, R> =>
    table.ensure ? runStorageCallback("ensure", () => table.ensure!()) : Effect.void;

  const rowKey = (key: string): SQLitePersistenceKey => ({ namespace, key });

  const storage = {
    getItem: (key: string) =>
      Effect.gen(function* () {
        const table = yield* tableEffect();
        yield* ensureTable(table);
        const currentSchemaVersion = yield* statementRowNumber("schema_version", schemaVersion);
        const row = yield* runStorageCallback("get", () => table.get(rowKey(key)));
        const validRow = row == null ? null : yield* sqlitePersistenceRowEffect(row);
        return validRow?.schemaVersion === currentSchemaVersion ? validRow.value : null;
      }),
    setItem: (key: string, value: string) =>
      Effect.gen(function* () {
        const table = yield* tableEffect();
        yield* ensureTable(table);
        const currentSchemaVersion = yield* statementRowNumber("schema_version", schemaVersion);
        const updatedAt = yield* runStorageCallback("now", now);
        const validUpdatedAt = yield* statementRowNumber("updated_at", updatedAt);
        yield* runStorageCallback("upsert", () => table.upsert({
          ...rowKey(key),
          schemaVersion: currentSchemaVersion,
          value,
          updatedAt: validUpdatedAt
        }));
      })
  } satisfies Omit<
    CollectionPersistenceStorage<E | EffectInputCallbackError | SQLitePersistenceInvalidRow | SQLitePersistenceInvalidTableName, R>,
    "removeItem"
  >;

  return {
    ...storage,
    removeItem: (key: string) =>
      Effect.gen(function* () {
        const table = yield* tableEffect();
        if (!table.delete) {
          return;
        }
        yield* ensureTable(table);
        yield* runStorageCallback("delete", () => table.delete!(rowKey(key)));
      })
  };
};

/**
 * SQLite persistence namespace for collection snapshot storage helpers.
 */
export namespace SQLitePersistence {
  /** Namespaced row key for one persisted collection snapshot. */
  export type Key = SQLitePersistenceKey;
  /** Persisted SQLite row shape used by the collection persistence driver. */
  export type Row = SQLitePersistenceRow;
  /** Effect-aware table Adapter for persistence rows. */
  export type Table<E = never, R = never> = SQLitePersistenceTable<E, R>;
  /** Adapter that resolves named persistence tables. */
  export type Driver<E = never, R = never> = SQLitePersistenceDriver<E, R>;
  /** SQL statement recorded by the in-memory statement database. */
  export type MemoryStatement = SQLiteMemoryStatement;
  /** In-memory statement database for tests and demos. */
  export type MemoryStatementDatabase = SQLiteMemoryStatementDatabase;
  /** Prepared statement shape for SQLite clients with `run` and `all`. */
  export type PreparedStatement<
    Row extends SQLiteStatementRow = SQLiteStatementRow,
    E = never,
    R = never
  > = SQLitePreparedStatement<Row, E, R>;
  /** SQLite client shape for adapters that expose `prepare`. */
  export type PreparedStatementDatabase<
    Row extends SQLiteStatementRow = SQLiteStatementRow,
    E = never,
    R = never
  > = SQLitePreparedStatementDatabase<Row, E, R>;
  /** Options for prepared-statement database adaptation. */
  export type PreparedStatementDatabaseOptions = SQLitePreparedStatementDatabaseOptions;
  /** SQLite statement parameter value supported by generated SQL. */
  export type StatementValue = SQLiteStatementValue;
  /** Positional SQLite statement parameter list. */
  export type StatementParams = SQLiteStatementParams;
  /** Row shape returned by generated SELECT statements. */
  export type StatementRow = SQLiteStatementRow;
  /** Minimal SQL statement database used by the persistence driver. */
  export type StatementDatabase<E = never, R = never> = SQLiteStatementDatabase<E, R>;
  /** Options for collection persistence stored in SQLite. */
  export type Options = SQLitePersistenceOptions;

  /** Create `CollectionPersistenceStorage` backed by SQLite. */
  export const storage = makeSQLitePersistenceStorage;
  /** Adapt a `prepare`/`run`/`all` SQLite client to a statement database. */
  export const preparedStatementDatabase = makeSQLitePreparedStatementDatabase;
  /** Build a persistence driver from a simple SQL statement database. */
  export const statementDriver = makeSQLiteStatementPersistenceDriver;
  /** Create an in-memory statement database for tests and demos. */
  export const memoryStatementDatabase = makeSQLiteMemoryStatementDatabase;
}
