import type { EffectInput } from "@effect-ui/core";
import { toEffect } from "@effect-ui/core";
import { Data, Effect } from "effect";
import type { CollectionPersistenceStorage } from "./collection-contract.js";

export const SQLITE_PERSISTENCE_DEFAULT_TABLE = "effect_ui_collection_persistence";
export const SQLITE_PERSISTENCE_DEFAULT_NAMESPACE = "effect-ui:collections";
export const SQLITE_PERSISTENCE_DEFAULT_SCHEMA_VERSION = 1;

/**
 * Namespaced key for one persisted collection snapshot.
 */
export interface SQLitePersistenceKey {
  readonly namespace: string;
  readonly key: string;
}

/**
 * Row shape stored by the SQLite persistence driver.
 */
export interface SQLitePersistenceRow extends SQLitePersistenceKey {
  readonly schemaVersion: number;
  readonly value: string;
  readonly updatedAt: number;
}

/**
 * Effect-aware table adapter for persistence rows.
 *
 * Implement this directly for custom SQLite clients, or use
 * `makeSQLiteStatementPersistenceDriver` for SQL statement based clients.
 */
export interface SQLitePersistenceTable<E = unknown, R = never> {
  readonly ensure?: () => EffectInput<void, E, R>;
  readonly get: (key: SQLitePersistenceKey) => EffectInput<SQLitePersistenceRow | null, E, R>;
  readonly upsert: (row: SQLitePersistenceRow) => EffectInput<void, E, R>;
  readonly delete?: (key: SQLitePersistenceKey) => EffectInput<void, E, R>;
}

/**
 * Driver that resolves named persistence tables.
 */
export interface SQLitePersistenceDriver<E = unknown, R = never> {
  readonly table: (name: string) => SQLitePersistenceTable<E, R>;
}

/**
 * SQLite parameter value supported by generated persistence SQL.
 */
export type SQLiteStatementValue = string | number | null;

export type SQLiteStatementParams = ReadonlyArray<SQLiteStatementValue>;

/**
 * Row shape returned by generated SELECT statements.
 */
export interface SQLiteStatementRow {
  readonly namespace?: unknown;
  readonly key?: unknown;
  readonly schema_version?: unknown;
  readonly schemaVersion?: unknown;
  readonly value?: unknown;
  readonly updated_at?: unknown;
  readonly updatedAt?: unknown;
}

/**
 * Minimal SQL statement database used by the SQLite persistence driver.
 */
export interface SQLiteStatementDatabase<E = unknown, R = never> {
  readonly execute: (sql: string, params?: SQLiteStatementParams) => EffectInput<void, E, R>;
  readonly select: (sql: string, params?: SQLiteStatementParams) => EffectInput<ReadonlyArray<SQLiteStatementRow>, E, R>;
}

/**
 * Prepared statement shape for clients with `run` and `all` methods.
 */
export interface SQLitePreparedStatement<
  Row extends SQLiteStatementRow = SQLiteStatementRow,
  E = unknown,
  R = never
> {
  readonly run: (...params: Array<SQLiteStatementValue>) => EffectInput<unknown, E, R>;
  readonly all: (...params: Array<SQLiteStatementValue>) => EffectInput<ReadonlyArray<Row>, E, R>;
}

/**
 * SQLite client shape for adapters that expose `prepare`.
 */
export interface SQLitePreparedStatementDatabase<
  Row extends SQLiteStatementRow = SQLiteStatementRow,
  E = unknown,
  R = never
> {
  readonly prepare: (sql: string) => EffectInput<SQLitePreparedStatement<Row, E, R>, E, R>;
}

/**
 * Options for the prepared-statement adapter.
 */
export interface SQLitePreparedStatementDatabaseOptions {
  readonly cache?: boolean;
}

/**
 * SQL statement recorded by the in-memory statement database.
 */
export interface SQLiteMemoryStatement {
  readonly sql: string;
  readonly params?: SQLiteStatementParams;
}

/**
 * In-memory implementation of the generated persistence SQL.
 *
 * Useful for tests and examples. It records statements and supports only the
 * SQL generated by `makeSQLiteStatementPersistenceDriver`.
 */
export interface SQLiteMemoryStatementDatabase extends SQLiteStatementDatabase<never, never> {
  readonly statements: ReadonlyArray<SQLiteMemoryStatement>;
  row(table: string, namespace: string, key: string): SQLitePersistenceRow | undefined;
  tableRows(table: string): ReadonlyArray<SQLitePersistenceRow>;
  clear(): void;
}

/**
 * Options for collection persistence stored in SQLite.
 */
export interface SQLitePersistenceOptions {
  readonly namespace?: string;
  readonly tableName?: string;
  readonly schemaVersion?: number;
  readonly now?: () => number;
}

/**
 * Error raised before generating SQL for an invalid table name.
 */
export class SQLitePersistenceInvalidTableName extends Data.TaggedError(
  "SQLitePersistenceInvalidTableName"
)<{
  readonly tableName: string;
  readonly reason: "Empty" | "ContainsNul";
  readonly guidance: string;
}> {}

/**
 * Error raised by the in-memory adapter for SQL outside the generated subset.
 */
export class SQLitePersistenceUnsupportedStatement extends Data.TaggedError(
  "SQLitePersistenceUnsupportedStatement"
)<{
  readonly sql: string;
  readonly operation: "tableName" | "execute" | "select";
  readonly guidance: string;
}> {}

const runInput = <A, E, R>(input: EffectInput<A, E, R>): Effect.Effect<A, E, R> =>
  toEffect(input);

const quoteIdentifier = (identifier: string): string => {
  if (identifier.length === 0 || identifier.includes("\0")) {
    throw new SQLitePersistenceInvalidTableName({
      tableName: identifier,
      reason: identifier.length === 0 ? "Empty" : "ContainsNul",
      guidance: "Use a non-empty SQLite table name that does not contain NUL bytes."
    });
  }

  return `"${identifier.replaceAll("\"", "\"\"")}"`;
};

const unquoteIdentifier = (identifier: string): string =>
  identifier.startsWith("\"") && identifier.endsWith("\"")
    ? identifier.slice(1, -1).replaceAll("\"\"", "\"")
    : identifier;

const sqlTableName = (sql: string): string => {
  const match =
    sql.match(/\bINTO\s+("[^"]*(?:""[^"]*)*")/i) ??
    sql.match(/\bFROM\s+("[^"]*(?:""[^"]*)*")/i) ??
    sql.match(/\bEXISTS\s+("[^"]*(?:""[^"]*)*")/i);
  if (!match?.[1]) {
    throw new SQLitePersistenceUnsupportedStatement({
      sql,
      operation: "tableName",
      guidance: "Use SQL generated by makeSQLiteStatementPersistenceDriver or extend the memory adapter parser."
    });
  }
  return unquoteIdentifier(match[1]);
};

const rowNumber = (value: unknown): number =>
  typeof value === "number" ? value : Number(value);

const rowString = (value: unknown): string =>
  typeof value === "string" ? value : String(value);

const statementParamList = (params?: SQLiteStatementParams): Array<SQLiteStatementValue> =>
  params === undefined ? [] : [...params];

const memoryRowId = (table: string, key: SQLitePersistenceKey): string =>
  `${table}\0${key.namespace}\0${key.key}`;

/**
 * Create an in-memory statement database that understands generated SQL.
 *
 * Use for tests or demos that need SQLite persistence behavior without a real
 * SQLite runtime.
 */
export const makeSQLiteMemoryStatementDatabase = (): SQLiteMemoryStatementDatabase => {
  const rows = new Map<string, SQLitePersistenceRow>();
  const statements: Array<SQLiteMemoryStatement> = [];

  const row = (table: string, namespace: string, key: string): SQLitePersistenceRow | undefined =>
    rows.get(memoryRowId(table, { namespace, key }));

  const tableRows = (table: string): ReadonlyArray<SQLitePersistenceRow> =>
    Array.from(rows.entries())
      .filter(([id]) => id.startsWith(`${table}\0`))
      .map(([, value]) => ({ ...value }));

  return {
    statements,
    execute: (sql, params) => {
      statements.push(params === undefined ? { sql } : { sql, params });
      const table = sqlTableName(sql);
      if (/^\s*CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\b/i.test(sql)) {
        return;
      }

      if (/^\s*INSERT\s+INTO\b/i.test(sql)) {
        const [namespace, key, schemaVersion, value, updatedAt] = params ?? [];
        rows.set(memoryRowId(table, {
          namespace: rowString(namespace),
          key: rowString(key)
        }), {
          namespace: rowString(namespace),
          key: rowString(key),
          schemaVersion: rowNumber(schemaVersion),
          value: rowString(value),
          updatedAt: rowNumber(updatedAt)
        });
        return;
      }

      if (/^\s*DELETE\s+FROM\b/i.test(sql)) {
        const [namespace, key] = params ?? [];
        rows.delete(memoryRowId(table, {
          namespace: rowString(namespace),
          key: rowString(key)
        }));
        return;
      }

      throw new SQLitePersistenceUnsupportedStatement({
        sql,
        operation: "execute",
        guidance: "The in-memory SQLite adapter supports generated CREATE, INSERT, and DELETE statements only."
      });
    },
    select: (sql, params) => {
      statements.push(params === undefined ? { sql } : { sql, params });
      if (!/^\s*SELECT\b/i.test(sql)) {
        throw new SQLitePersistenceUnsupportedStatement({
          sql,
          operation: "select",
          guidance: "The in-memory SQLite adapter supports generated SELECT statements only."
        });
      }

      const table = sqlTableName(sql);
      const [namespace, key] = params ?? [];
      const current = row(table, rowString(namespace), rowString(key));
      return current
        ? [{
            namespace: current.namespace,
            key: current.key,
            schema_version: current.schemaVersion,
            value: current.value,
            updated_at: current.updatedAt
          }]
        : [];
    },
    row,
    tableRows,
    clear: () => {
      rows.clear();
      statements.length = 0;
    }
  };
};

/**
 * Adapt a `prepare`/`run`/`all` SQLite client to the statement database shape.
 *
 * Enable `cache` to reuse prepared statements by SQL string.
 */
export const makeSQLitePreparedStatementDatabase = <
  Row extends SQLiteStatementRow = SQLiteStatementRow,
  E = unknown,
  R = never
>(
  database: SQLitePreparedStatementDatabase<Row, E, R>,
  options: SQLitePreparedStatementDatabaseOptions = {}
): SQLiteStatementDatabase<E, R> => {
  const cache = options.cache === true
    ? new Map<string, SQLitePreparedStatement<Row, E, R>>()
    : undefined;

  const prepare = (sql: string): Effect.Effect<SQLitePreparedStatement<Row, E, R>, E, R> =>
    Effect.gen(function* () {
      const cached = cache?.get(sql);
      if (cached) {
        return cached;
      }

      const statement = yield* runInput(database.prepare(sql));
      cache?.set(sql, statement);
      return statement;
    });

  return {
    execute: (sql, params): Effect.Effect<void, E, R> =>
      Effect.flatMap(prepare(sql), (statement) =>
        Effect.asVoid(runInput(statement.run(...statementParamList(params))))
      ),
    select: (sql, params): Effect.Effect<ReadonlyArray<SQLiteStatementRow>, E, R> =>
      Effect.flatMap(prepare(sql), (statement) =>
        runInput(statement.all(...statementParamList(params)))
      )
  };
};

/**
 * Build a persistence driver from a simple SQL statement database.
 *
 * The driver creates the table if needed, stores snapshots by namespace/key,
 * and quotes table names defensively.
 */
export const makeSQLiteStatementPersistenceDriver = <E = unknown, R = never>(
  database: SQLiteStatementDatabase<E, R>
): SQLitePersistenceDriver<E, R> => ({
  table: (name) => {
    const table = quoteIdentifier(name);
    return {
      ensure: () =>
        database.execute(
          `CREATE TABLE IF NOT EXISTS ${table} (` +
            "\"namespace\" TEXT NOT NULL, " +
            "\"key\" TEXT NOT NULL, " +
            "\"schema_version\" INTEGER NOT NULL, " +
            "\"value\" TEXT NOT NULL, " +
            "\"updated_at\" INTEGER NOT NULL, " +
            "PRIMARY KEY (\"namespace\", \"key\")" +
          ")"
        ),
      get: (key) =>
        Effect.gen(function* () {
          const rows = yield* runInput(database.select(
            `SELECT "namespace", "key", "schema_version", "value", "updated_at" FROM ${table} ` +
              "WHERE \"namespace\" = ? AND \"key\" = ? LIMIT 1",
            [key.namespace, key.key]
          ));
          const row = rows[0];
          if (!row) {
            return null;
          }

          return {
            namespace: rowString(row.namespace),
            key: rowString(row.key),
            schemaVersion: rowNumber(row.schemaVersion ?? row.schema_version),
            value: rowString(row.value),
            updatedAt: rowNumber(row.updatedAt ?? row.updated_at)
          } satisfies SQLitePersistenceRow;
        }),
      upsert: (row) =>
        database.execute(
          `INSERT INTO ${table} ("namespace", "key", "schema_version", "value", "updated_at") ` +
            "VALUES (?, ?, ?, ?, ?) " +
            "ON CONFLICT(\"namespace\", \"key\") DO UPDATE SET " +
            "\"schema_version\" = excluded.\"schema_version\", " +
            "\"value\" = excluded.\"value\", " +
            "\"updated_at\" = excluded.\"updated_at\"",
          [row.namespace, row.key, row.schemaVersion, row.value, row.updatedAt]
        ),
      delete: (key) =>
        database.execute(
          `DELETE FROM ${table} WHERE "namespace" = ? AND "key" = ?`,
          [key.namespace, key.key]
        )
    };
  }
});

/**
 * Create `CollectionPersistenceStorage` backed by SQLite.
 *
 * Schema-version mismatches read as `null`, letting callers fall back to a
 * fresh load. Database errors and services flow through the returned storage
 * error and requirement channels.
 *
 * @example
 * const storage = makeSQLitePersistenceStorage(
 *   makeSQLiteStatementPersistenceDriver(database)
 * )
 */
export const makeSQLitePersistenceStorage = <E = unknown, R = never>(
  driver: SQLitePersistenceDriver<E, R>,
  options: SQLitePersistenceOptions = {}
): CollectionPersistenceStorage<E, R> => {
  const namespace = options.namespace ?? SQLITE_PERSISTENCE_DEFAULT_NAMESPACE;
  const tableName = options.tableName ?? SQLITE_PERSISTENCE_DEFAULT_TABLE;
  const schemaVersion = options.schemaVersion ?? SQLITE_PERSISTENCE_DEFAULT_SCHEMA_VERSION;
  const now = options.now ?? Date.now;
  const table = driver.table(tableName);
  const ensure = table.ensure;
  const deleteRow = table.delete;

  const ensureTable = (): Effect.Effect<void, E, R> =>
    ensure ? runInput(ensure()) : Effect.void;

  const rowKey = (key: string): SQLitePersistenceKey => ({ namespace, key });

  const storage = {
    getItem: (key: string) =>
      Effect.gen(function* () {
        yield* ensureTable();
        const row = yield* runInput(table.get(rowKey(key)));
        return row?.schemaVersion === schemaVersion ? row.value : null;
      }),
    setItem: (key: string, value: string) =>
      Effect.gen(function* () {
        yield* ensureTable();
        yield* runInput(table.upsert({
          ...rowKey(key),
          schemaVersion,
          value,
          updatedAt: now()
        }));
      })
  } satisfies Omit<CollectionPersistenceStorage<E, R>, "removeItem">;

  return deleteRow
    ? {
        ...storage,
        removeItem: (key: string) =>
          Effect.gen(function* () {
            yield* ensureTable();
            yield* runInput(deleteRow(rowKey(key)));
          })
      }
    : storage;
};

/**
 * SQLite persistence namespace for collection snapshot storage helpers.
 */
export namespace SQLitePersistence {
  export type Key = SQLitePersistenceKey;
  export type Row = SQLitePersistenceRow;
  export type Table<E = unknown, R = never> = SQLitePersistenceTable<E, R>;
  export type Driver<E = unknown, R = never> = SQLitePersistenceDriver<E, R>;
  export type MemoryStatement = SQLiteMemoryStatement;
  export type MemoryStatementDatabase = SQLiteMemoryStatementDatabase;
  export type PreparedStatement<
    Row extends SQLiteStatementRow = SQLiteStatementRow,
    E = unknown,
    R = never
  > = SQLitePreparedStatement<Row, E, R>;
  export type PreparedStatementDatabase<
    Row extends SQLiteStatementRow = SQLiteStatementRow,
    E = unknown,
    R = never
  > = SQLitePreparedStatementDatabase<Row, E, R>;
  export type PreparedStatementDatabaseOptions = SQLitePreparedStatementDatabaseOptions;
  export type StatementValue = SQLiteStatementValue;
  export type StatementParams = SQLiteStatementParams;
  export type StatementRow = SQLiteStatementRow;
  export type StatementDatabase<E = unknown, R = never> = SQLiteStatementDatabase<E, R>;
  export type Options = SQLitePersistenceOptions;

  /** Create `CollectionPersistenceStorage` backed by SQLite. */
  export const storage = makeSQLitePersistenceStorage;
  /** Adapt a `prepare`/`run`/`all` SQLite client to a statement database. */
  export const preparedStatementDatabase = makeSQLitePreparedStatementDatabase;
  /** Build a persistence driver from a simple SQL statement database. */
  export const statementDriver = makeSQLiteStatementPersistenceDriver;
  /** Create an in-memory statement database for tests and demos. */
  export const memoryStatementDatabase = makeSQLiteMemoryStatementDatabase;
}
