// This file is generated by @effect-ui/start. Do not edit.

import type { Route } from "@effect-ui/core";

import { Route as route_root } from "./routes/index.js";

const route_root_path: "/" = route_root.path;

export { route_root };

export const routes = [route_root] as const;
export const routeTree = routes;
export const routeById = {
  "route_root": route_root
} as const;
export const routeByPath = {
  "/": route_root
} as const;

export const fileRouteModules = [
  {
    "id": "index",
    "kind": "Route",
    "routeId": "route_root",
    "moduleId": "src/routes/index.ts",
    "filePath": "src/routes/index.ts",
    "routePath": "/",
    "segments": [],
    "params": [],
    "exportName": "Route"
  }
] as const;
export const fileRouteMetadata = [
  {
    "routeId": "route_root",
    "routePath": "/",
    "routeModule": {
      "id": "index",
      "kind": "Route",
      "routeId": "route_root",
      "moduleId": "src/routes/index.ts",
      "filePath": "src/routes/index.ts",
      "routePath": "/",
      "segments": [],
      "params": [],
      "exportName": "Route"
    },
    "layouts": [],
    "metadataModules": []
  }
] as const;

export type RouteTree = typeof routeTree;
export type RouteById = typeof routeById;
export type RouteByPath = typeof routeByPath;
export type FileRoute = RouteTree[number];
export type FileRouteId = keyof RouteById;
export type FileRoutePath = keyof RouteByPath;
export type FileRouteByPath = RouteByPath;
export type FileRouteParamsById = { readonly [Id in FileRouteId]: Route.Params<RouteById[Id]> };
export type FileRouteSearchById = { readonly [Id in FileRouteId]: Route.Search<RouteById[Id]> };
export type FileRouteHrefOptionsById = { readonly [Id in FileRouteId]: Route.HrefOptions<RouteById[Id]> };
export type FileRouteHrefOptions<Id extends FileRouteId> = FileRouteHrefOptionsById[Id];
export type FileRouteParamsByPath = { readonly [Path in keyof FileRouteByPath]: Route.Params<FileRouteByPath[Path]> };
export type FileRouteSearchByPath = { readonly [Path in keyof FileRouteByPath]: Route.Search<FileRouteByPath[Path]> };
export type FileRouteHrefOptionsByPath = { readonly [Path in keyof FileRouteByPath]: Route.HrefOptions<FileRouteByPath[Path]> };
export type FileRouteModules = typeof fileRouteModules;
export type FileRouteMetadata = typeof fileRouteMetadata;
export default routes;
