import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { Effect } from "effect";
import {
  hydrationScriptId,
  streamHydrationAttribute,
  type StartHydrationChunk,
  type StartHydrationPayload,
} from "@sunfall/arc-start";
import { app } from "./app-definition.js";
import { WelcomeRef } from "./starter.js";
import {
  hrefById,
  hrefByPath,
  routeById,
  routeByPath,
  routes,
  type FileRouteHrefOptionsById,
} from "./routeTree.gen.js";
import { handleRequest } from "./server.js";

const htmlJsonScriptPattern = /<script\b([^>]*)>([\s\S]*?)<\/script>/g;

const rootHydrationPayloadFrom = (html: string): StartHydrationPayload => {
  for (const match of html.matchAll(htmlJsonScriptPattern)) {
    if ((match[1] ?? "").includes(`id="${hydrationScriptId}"`)) {
      return JSON.parse(match[2] ?? "") as StartHydrationPayload;
    }
  }

  expect.fail("Root hydration script not found.");
};

const streamHydrationChunksFrom = (html: string): ReadonlyArray<StartHydrationChunk> =>
  Array.from(html.matchAll(htmlJsonScriptPattern))
    .filter((match) => match[1]?.includes(streamHydrationAttribute))
    .map((match) => JSON.parse(match[2] ?? "") as StartHydrationChunk);

const resourcePairs = (payload: StartHydrationPayload): ReadonlySet<string> =>
  new Set(payload.resources.map((resource) => JSON.stringify([resource.name, resource.key])));

describe("basic starter", () => {
  it("renders the SSR shell and route-owned Resource preload", () =>
    Effect.runPromise(
      Effect.gen(function* () {
        const response = yield* Effect.scoped(
          app.runtime.provide(handleRequest(new Request("https://starter.test/"))),
        );
        const html = yield* Effect.tryPromise(() => response.text());
        const rootPairs = resourcePairs(rootHydrationPayloadFrom(html));
        const streamedPairs = new Set(
          streamHydrationChunksFrom(html).flatMap((chunk) => [...resourcePairs(chunk.payload)]),
        );

        expect(response.status).toBe(200);
        expect(response.headers.get("x-sunfall-arc-starter")).toBe("basic");
        expect(html).toContain("Hello, Sunfall Arc.");
        expect(html).toContain("__SUNFALL_ARC_HYDRATION__");
        expect(html).toContain("data-sunfall-arc-hydration-chunk");
        expect([...rootPairs]).toEqual([]);
        expect(streamHydrationChunksFrom(html)).toHaveLength(1);
        expect([...streamedPairs]).toContain(
          JSON.stringify([WelcomeRef.family.options.name, WelcomeRef.key]),
        );
        expect([...streamedPairs].filter((pair) => rootPairs.has(pair))).toEqual([]);
      }),
    ));

  it("pins the generated route definitions artifact", () => {
    const hrefOptions: FileRouteHrefOptionsById["route_root"] = {};
    const source = readFileSync(new URL("./routeTree.gen.ts", import.meta.url), "utf8");

    expect(source).toContain("// This file is generated by @sunfall/arc-start. Do not edit.");
    expect(routes).toEqual([routeById.route_root]);
    expect(routeByPath["/"]).toBe(routeById.route_root);
    expect(routeById.route_root.path).toBe("/");
    expect(hrefOptions).toEqual({});
    expect(hrefById("route_root")).toBe("/");
    expect(hrefByPath("/")).toBe("/");
  });
});
