import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { Effect } from "effect";
import { streamHydrationAttribute, type StartHydrationChunk } from "@effect-ui/start";
import { makeRecipeSlug, RecipeBySlug, RecipeIndexRef } from "./content.js";
import {
  hrefById,
  hrefByPath,
  routeById,
  routeByPath,
  routes,
  type FileRouteHrefOptionsById,
} from "./routeTree.gen.js";
import { handleRequest, serverApp } from "./server.js";
import {
  docsSiteStaticLinks,
  docsSiteStaticOutputPath,
  docsSiteStaticSeedPathsEffect,
  renderDocsSiteStaticPageEffect,
} from "./static-export.js";

const htmlJsonScriptPattern = /<script\b([^>]*)>([\s\S]*?)<\/script>/g;

const streamHydrationChunksFrom = (html: string): ReadonlyArray<StartHydrationChunk> =>
  Array.from(html.matchAll(htmlJsonScriptPattern))
    .filter((match) => match[1]?.includes(streamHydrationAttribute))
    .map((match) => JSON.parse(match[2] ?? "") as StartHydrationChunk);

const resourcePairs = (chunks: ReadonlyArray<StartHydrationChunk>): ReadonlySet<string> =>
  new Set(
    chunks.flatMap((chunk) =>
      chunk.payload.resources.map((resource) => JSON.stringify([resource.name, resource.key])),
    ),
  );

describe("docs site", () => {
  it("renders the cookbook index through route-owned Resource preload", () =>
    Effect.runPromise(
      Effect.gen(function* () {
        const response = yield* Effect.scoped(
          serverApp.runtime.provide(handleRequest(new Request("https://docs.test/cookbook"))),
        );
        const html = yield* Effect.tryPromise(() => response.text());
        const pairs = resourcePairs(streamHydrationChunksFrom(html));

        expect(response.status).toBe(200);
        expect(response.headers.get("x-effect-ui-docs")).toBe("cookbook");
        expect(html).toContain("Idiomatic Effect UI examples");
        expect(html).toContain("Resource from a server function");
        expect(html).toContain("Progressive Start action form");
        expect([...pairs]).toContain(
          JSON.stringify([RecipeIndexRef.family.options.name, RecipeIndexRef.key]),
        );
      }),
    ));

  it("renders a recipe detail page and streams the recipe Resource", () =>
    Effect.runPromise(
      Effect.gen(function* () {
        const slug = makeRecipeSlug("semantic-invalidation");
        const ref = RecipeBySlug(slug);
        const response = yield* Effect.scoped(
          serverApp.runtime.provide(
            handleRequest(new Request("https://docs.test/cookbook/semantic-invalidation")),
          ),
        );
        const html = yield* Effect.tryPromise(() => response.text());
        const pairs = resourcePairs(streamHydrationChunksFrom(html));

        expect(response.status).toBe(200);
        expect(html).toContain("Semantic invalidation tags");
        expect(html).toContain("Tags describe domain facts");
        expect(html).toContain("Related recipes");
        expect([...pairs]).toContain(
          JSON.stringify([RecipeIndexRef.family.options.name, RecipeIndexRef.key]),
        );
        expect([...pairs]).toContain(JSON.stringify([ref.family.options.name, ref.key]));
      }),
    ));

  it("pins the generated docs route artifact", () => {
    const cookbookHrefOptions: FileRouteHrefOptionsById["route_cookbook"] = {};
    const recipeHrefOptions: FileRouteHrefOptionsById["route_cookbook_$slug"] = {
      params: { slug: makeRecipeSlug("resource-from-server-function") },
    };
    const source = readFileSync(new URL("./routeTree.gen.ts", import.meta.url), "utf8");

    expect(source).toContain("// This file is generated by @effect-ui/start. Do not edit.");
    expect(routes).toEqual([
      routeById.route_root,
      routeById.route_cookbook,
      routeById.route_cookbook_$slug,
    ]);
    expect(routeByPath["/cookbook/:slug"]).toBe(routeById.route_cookbook_$slug);
    expect(cookbookHrefOptions).toEqual({});
    expect(recipeHrefOptions.params.slug).toBe("resource-from-server-function");
    expect(hrefById("route_cookbook")).toBe("/cookbook");
    expect(hrefByPath("/cookbook/:slug", recipeHrefOptions)).toBe(
      "/cookbook/resource-from-server-function",
    );
  });

  it("plans and renders docs static export pages", () =>
    Effect.runPromise(
      Effect.gen(function* () {
        const paths = yield* docsSiteStaticSeedPathsEffect;
        const page = yield* renderDocsSiteStaticPageEffect(
          "/cookbook/resource-from-server-function",
        );
        const links = docsSiteStaticLinks(page.html, page.path);

        expect(paths).toContain("/");
        expect(paths).toContain("/cookbook");
        expect(paths).toContain("/cookbook/resource-from-server-function");
        expect(page.status).toBe(200);
        expect(page.html).toContain("Resource from a server function");
        expect(links).toContain("/cookbook/semantic-invalidation");
        expect(docsSiteStaticOutputPath("/cookbook/resource-from-server-function")).toBe(
          "cookbook/resource-from-server-function/index.html",
        );
      }),
    ));
});
