// This file is generated by @effect-ui/start. Do not edit.

import { Route } from "@effect-ui/core";

import { Route as route_root } from "./routes/index.js";
import { Route as route_cookbook } from "./routes/cookbook/index.js";
import { Route as route_cookbook_$slug } from "./routes/cookbook/$slug.js";

const route_root_path: "/" = route_root.path;
const route_cookbook_path: "/cookbook" = route_cookbook.path;
const route_cookbook_$slug_path: "/cookbook/:slug" = route_cookbook_$slug.path;

export { route_root, route_cookbook, route_cookbook_$slug };

/** Ordered app-specific route definitions discovered from Start file routes. */
export const routes = [route_root, route_cookbook, route_cookbook_$slug] as const;
/** Alias for `routes`, kept for router-style naming and generated-file ergonomics. */
export const routeTree = routes;
/** Map from generated route id to the exact route definition for that file route. */
export const routeById = {
  route_root: route_root,
  route_cookbook: route_cookbook,
  route_cookbook_$slug: route_cookbook_$slug,
} as const;
/** Map from route path pattern to the exact route definition for that file route. */
export const routeByPath = {
  "/": route_root,
  "/cookbook": route_cookbook,
  "/cookbook/:slug": route_cookbook_$slug,
} as const;
/** Map from route path pattern to generated route id. */
export const routeIdByPath = {
  "/": "route_root",
  "/cookbook": "route_cookbook",
  "/cookbook/:slug": "route_cookbook_$slug",
} as const;
/** Builds a typed href for a generated route id. */
export const hrefById = <Id extends RouteId>(
  id: Id,
  ...args: Route.HrefArgs<RouteById[Id]>
): string => Route.href(routeById[id], ...args);
/** Builds a typed href for a generated route path pattern. */
export const hrefByPath = <Path extends RoutePath>(
  path: Path,
  ...args: Route.HrefArgs<RouteByPath[Path]>
): string => Route.href(routeByPath[path], ...args);

/** Layout modules that wrap each generated route, ordered from source-scope root to leaf. */
export const fileRouteLayoutsById = {
  route_root: [],
  route_cookbook: [],
  route_cookbook_$slug: [],
} as const;
/** Nearest source-scoped error boundary module for each generated route, when one exists. */
export const fileRouteErrorBoundaryById = {} as const;
/** Metadata modules scoped to each generated route by source id, ordered from root to leaf. */
export const fileRouteMetadataById = {
  route_root: [],
  route_cookbook: [],
  route_cookbook_$slug: [],
} as const;
/** Returns layout modules for a generated route id. */
export const layoutsById = <Id extends RouteId>(id: Id): FileRouteLayouts<Id> =>
  fileRouteLayoutsById[id];
/** Returns layout modules for a generated route path pattern. */
export const layoutsByPath = <Path extends RoutePath>(
  path: Path,
): FileRouteLayouts<RouteIdByPath[Path]> => layoutsById(routeIdByPath[path]);
/** Returns the nearest error boundary module for a generated route id, when one exists. */
export const errorBoundaryById = <Id extends RouteId>(id: Id): FileRouteErrorBoundary<Id> =>
  (fileRouteErrorBoundaryById as Partial<Record<RouteId, unknown>>)[
    id
  ] as FileRouteErrorBoundary<Id>;
/** Returns the nearest error boundary module for a generated route path pattern, when one exists. */
export const errorBoundaryByPath = <Path extends RoutePath>(
  path: Path,
): FileRouteErrorBoundary<RouteIdByPath[Path]> => errorBoundaryById(routeIdByPath[path]);
/** Returns metadata modules for a generated route id. */
export const metadataById = <Id extends RouteId>(id: Id): FileRouteMetadataModules<Id> =>
  fileRouteMetadataById[id];
/** Returns metadata modules for a generated route path pattern. */
export const metadataByPath = <Path extends RoutePath>(
  path: Path,
): FileRouteMetadataModules<RouteIdByPath[Path]> => metadataById(routeIdByPath[path]);

/** Route, layout, error boundary, and metadata modules discovered by Start. */
export const fileRouteModules = [
  {
    id: "index",
    kind: "Route",
    routeId: "route_root",
    moduleId: "src/routes/index.ts",
    filePath: "src/routes/index.ts",
    routePath: "/",
    segments: [],
    params: [],
    exportName: "Route",
  },
  {
    id: "cookbook/index",
    kind: "Route",
    routeId: "route_cookbook",
    moduleId: "src/routes/cookbook/index.ts",
    filePath: "src/routes/cookbook/index.ts",
    routePath: "/cookbook",
    segments: [
      {
        _tag: "Static",
        value: "cookbook",
      },
    ],
    params: [],
    exportName: "Route",
  },
  {
    id: "cookbook/$slug",
    kind: "Route",
    routeId: "route_cookbook_$slug",
    moduleId: "src/routes/cookbook/$slug.ts",
    filePath: "src/routes/cookbook/$slug.ts",
    routePath: "/cookbook/:slug",
    segments: [
      {
        _tag: "Static",
        value: "cookbook",
      },
      {
        _tag: "Dynamic",
        name: "slug",
        optional: false,
      },
    ],
    params: [
      {
        name: "slug",
        optional: false,
      },
    ],
    exportName: "Route",
  },
] as const;
/** Parent, layout, error boundary, and metadata relationships for each generated route. */
export const fileRouteMetadata = [
  {
    routeId: "route_root",
    routePath: "/",
    routeModule: {
      id: "index",
      kind: "Route",
      routeId: "route_root",
      moduleId: "src/routes/index.ts",
      filePath: "src/routes/index.ts",
      routePath: "/",
      segments: [],
      params: [],
      exportName: "Route",
    },
    layouts: [],
    metadataModules: [],
  },
  {
    routeId: "route_cookbook",
    routePath: "/cookbook",
    routeModule: {
      id: "cookbook/index",
      kind: "Route",
      routeId: "route_cookbook",
      moduleId: "src/routes/cookbook/index.ts",
      filePath: "src/routes/cookbook/index.ts",
      routePath: "/cookbook",
      segments: [
        {
          _tag: "Static",
          value: "cookbook",
        },
      ],
      params: [],
      exportName: "Route",
    },
    parentRouteId: "route_root",
    parentRoutePath: "/",
    layouts: [],
    metadataModules: [],
  },
  {
    routeId: "route_cookbook_$slug",
    routePath: "/cookbook/:slug",
    routeModule: {
      id: "cookbook/$slug",
      kind: "Route",
      routeId: "route_cookbook_$slug",
      moduleId: "src/routes/cookbook/$slug.ts",
      filePath: "src/routes/cookbook/$slug.ts",
      routePath: "/cookbook/:slug",
      segments: [
        {
          _tag: "Static",
          value: "cookbook",
        },
        {
          _tag: "Dynamic",
          name: "slug",
          optional: false,
        },
      ],
      params: [
        {
          name: "slug",
          optional: false,
        },
      ],
      exportName: "Route",
    },
    parentRouteId: "route_cookbook",
    parentRoutePath: "/cookbook",
    layouts: [],
    metadataModules: [],
  },
] as const;

/** Tuple type for the generated app-specific route tree. */
export type RouteTree = typeof routeTree;
/** Map type keyed by generated route id. */
export type RouteById = typeof routeById;
/** Map type keyed by route path pattern. */
export type RouteByPath = typeof routeByPath;
/** Map type from route path pattern to generated route id. */
export type RouteIdByPath = typeof routeIdByPath;
/** Union of every generated route definition. */
export type FileRoute = RouteTree[number];
/** Union of generated route ids such as `route_projects_$id`. */
export type FileRouteId = keyof RouteById;
/** Union of generated route path patterns such as `/projects/:id`. */
export type FileRoutePath = keyof RouteByPath;
/** Route path lookup map preserved for path-keyed helper types. */
export type FileRouteByPath = RouteByPath;
/** Params for each generated route id. */
export type FileRouteParamsById = { readonly [Id in FileRouteId]: Route.Params<RouteById[Id]> };
/** Search values for each generated route id. */
export type FileRouteSearchById = { readonly [Id in FileRouteId]: Route.Search<RouteById[Id]> };
/** Href options for each generated route id. */
export type FileRouteHrefOptionsById = {
  readonly [Id in FileRouteId]: Route.HrefOptions<RouteById[Id]>;
};
/** Href options for one generated route id. */
export type FileRouteHrefOptions<Id extends FileRouteId> = FileRouteHrefOptionsById[Id];
/** Href arguments for each generated route id. */
export type FileRouteHrefArgsById = { readonly [Id in FileRouteId]: Route.HrefArgs<RouteById[Id]> };
/** Href arguments for one generated route id. */
export type FileRouteHrefArgs<Id extends FileRouteId> = FileRouteHrefArgsById[Id];
/** Params for each generated route path pattern. */
export type FileRouteParamsByPath = {
  readonly [Path in keyof FileRouteByPath]: Route.Params<FileRouteByPath[Path]>;
};
/** Search values for each generated route path pattern. */
export type FileRouteSearchByPath = {
  readonly [Path in keyof FileRouteByPath]: Route.Search<FileRouteByPath[Path]>;
};
/** Href options for each generated route path pattern. */
export type FileRouteHrefOptionsByPath = {
  readonly [Path in keyof FileRouteByPath]: Route.HrefOptions<FileRouteByPath[Path]>;
};
/** Href arguments for each generated route path pattern. */
export type FileRouteHrefArgsByPath = {
  readonly [Path in keyof FileRouteByPath]: Route.HrefArgs<FileRouteByPath[Path]>;
};
/** Route match narrowed to one generated route path pattern. */
export type FileRouteMatch<Path extends FileRoutePath> = Route.Match<FileRouteByPath[Path]>;
/** Layout modules keyed by generated route id. */
export type FileRouteLayoutsById = typeof fileRouteLayoutsById;
/** Error boundary modules keyed by generated route id when present. */
export type FileRouteErrorBoundaryById = typeof fileRouteErrorBoundaryById;
/** Metadata modules keyed by generated route id. */
export type FileRouteMetadataById = typeof fileRouteMetadataById;
/** Layout modules for one generated route id. */
export type FileRouteLayouts<Id extends FileRouteId> = FileRouteLayoutsById[Id];
/** Error boundary module for one generated route id, or undefined when none is scoped. */
export type FileRouteErrorBoundary<Id extends FileRouteId> =
  Id extends keyof FileRouteErrorBoundaryById ? FileRouteErrorBoundaryById[Id] : undefined;
/** Metadata modules for one generated route id. */
export type FileRouteMetadataModules<Id extends FileRouteId> = FileRouteMetadataById[Id];
/** Friendly alias for the generated route id union. */
export type RouteId = FileRouteId;
/** Friendly alias for the generated route path union. */
export type RoutePath = FileRoutePath;
/** Friendly alias for params keyed by generated route id. */
export type ParamsById = FileRouteParamsById;
/** Friendly alias for search values keyed by generated route id. */
export type SearchById = FileRouteSearchById;
/** Friendly alias for href options keyed by generated route id. */
export type HrefById = FileRouteHrefOptionsById;
/** Friendly alias for href options for one generated route id. */
export type Href<Id extends RouteId> = FileRouteHrefOptions<Id>;
/** Friendly alias for href arguments keyed by generated route id. */
export type HrefArgsById = FileRouteHrefArgsById;
/** Friendly alias for href arguments for one generated route id. */
export type HrefArgs<Id extends RouteId> = FileRouteHrefArgs<Id>;
/** Friendly alias for params keyed by generated route path. */
export type ParamsByPath = FileRouteParamsByPath;
/** Friendly alias for search values keyed by generated route path. */
export type SearchByPath = FileRouteSearchByPath;
/** Friendly alias for href options keyed by generated route path. */
export type HrefByPath = FileRouteHrefOptionsByPath;
/** Friendly alias for href arguments keyed by generated route path. */
export type HrefArgsByPath = FileRouteHrefArgsByPath;
/** Friendly alias for route matches narrowed by generated route path. */
export type Match<Path extends RoutePath> = FileRouteMatch<Path>;
/** Narrows a broad route match to one generated route path pattern. */
export const isRoutePathMatch = <Path extends FileRoutePath>(
  path: Path,
  match: Route.Match<FileRoute> | undefined,
): match is FileRouteMatch<Path> => match?.route.path === path;
/** Static metadata for all file-route modules discovered by Start. */
export type FileRouteModules = typeof fileRouteModules;
/** Static parent/layout/error/metadata relationships for generated routes. */
export type FileRouteMetadata = typeof fileRouteMetadata;
/** Default generated route tree export for router-style imports. */
export default routes;
