import { Data } from "effect";
import {
  describeFileRouteManifest,
  type FileRouteManifest,
  type FileRouteManifestEntry
} from "./file-routes.js";

export interface FileRouteDefinitionsModuleOptions {
  readonly generatedFile?: string;
  readonly importMode?: "relative" | "rootAbsolute";
  readonly routeModuleExportName?: string;
}

export interface FileRouteModuleReference {
  readonly entry: FileRouteManifestEntry;
  readonly importName: string;
  readonly identifier: string;
  readonly importSpecifier: string;
}

export interface GeneratedFileRouteDefinitionsModuleOptions
  extends FileRouteDefinitionsModuleOptions {
  readonly header?: string;
}

export class FileRouteDefinitionsModuleInvalidIdentifier extends Data.TaggedError(
  "FileRouteDefinitionsModuleInvalidIdentifier"
)<{
  readonly routeId: string;
  readonly routePath: string;
}> {}

export class FileRouteDefinitionsModuleInvalidExportName extends Data.TaggedError(
  "FileRouteDefinitionsModuleInvalidExportName"
)<{
  readonly exportName: string;
}> {}

const defaultGeneratedFileRouteDefinitionsFile = "src/routeTree.gen.ts";
const defaultRouteModuleExportName = "Route";
export const defaultGeneratedFileRouteDefinitionsHeader =
  "// This file is generated by @effect-ui/start. Do not edit.";
const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const asRouteIdentifier = (entry: FileRouteManifestEntry): string => {
  const routeId = String(entry.routeId);
  if (!identifierPattern.test(routeId)) {
    throw new FileRouteDefinitionsModuleInvalidIdentifier({
      routeId,
      routePath: entry.routePath
    });
  }
  return routeId;
};

const stringLiteral = (value: string): string => JSON.stringify(value);

const normalizePath = (path: string): string =>
  path
    .replace(/\\/g, "/")
    .replace(/\/+/g, "/")
    .replace(/\/$/, "");

const stripLeadingCurrentDirectory = (path: string): string =>
  path.startsWith("./") ? path.slice(2) : path;

const withRelativePrefix = (specifier: string): string =>
  specifier.startsWith(".") ? specifier : `./${specifier}`;

const isAbsolutePath = (path: string): boolean => path.startsWith("/");

const dirnamePath = (path: string): string => {
  const normalized = normalizePath(path);
  const slash = normalized.lastIndexOf("/");
  if (slash === -1) {
    return ".";
  }
  if (slash === 0) {
    return "/";
  }
  return normalized.slice(0, slash);
};

const extnamePath = (path: string): string => {
  const normalized = normalizePath(path);
  const slash = normalized.lastIndexOf("/");
  const dot = normalized.lastIndexOf(".");
  return dot > slash ? normalized.slice(dot) : "";
};

const splitRelativePath = (path: string): readonly string[] =>
  normalizePath(path)
    .replace(/^\/+/, "")
    .split("/")
    .filter((part) => part.length > 0 && part !== ".");

const relativePath = (from: string, target: string): string => {
  const fromParts = splitRelativePath(from);
  const targetParts = splitRelativePath(target);
  let common = 0;

  while (
    common < fromParts.length &&
    common < targetParts.length &&
    fromParts[common] === targetParts[common]
  ) {
    common++;
  }

  const parentParts = fromParts.slice(common).map(() => "..");
  const childParts = targetParts.slice(common);
  return [...parentParts, ...childParts].join("/") || ".";
};

const runtimeModulePath = (moduleId: string): string => {
  const normalized = normalizePath(moduleId).split(/[?#]/, 1)[0] ?? moduleId;
  const extension = extnamePath(normalized);
  switch (extension) {
    case ".ts":
    case ".tsx":
      return `${normalized.slice(0, -extension.length)}.js`;
    case ".mts":
      return `${normalized.slice(0, -extension.length)}.mjs`;
    case ".cts":
      return `${normalized.slice(0, -extension.length)}.cjs`;
    default:
      return normalized;
  }
};

const relativeImportSpecifier = (
  moduleId: string,
  generatedFile: string
): string => {
  const source = runtimeModulePath(moduleId);
  const fromDirectory = dirnamePath(stripLeadingCurrentDirectory(normalizePath(generatedFile)));
  const target = stripLeadingCurrentDirectory(source);
  const specifier = isAbsolutePath(fromDirectory) === isAbsolutePath(target)
    ? relativePath(fromDirectory, target)
    : relativePath(fromDirectory.replace(/^\/+/, ""), target.replace(/^\/+/, ""));

  return withRelativePrefix(normalizePath(specifier));
};

const rootAbsoluteImportSpecifier = (moduleId: string): string => {
  const source = runtimeModulePath(moduleId);
  return source.startsWith("/")
    ? source
    : `/${stripLeadingCurrentDirectory(source)}`;
};

const routeModuleImportSpecifier = (
  entry: FileRouteManifestEntry,
  options: FileRouteDefinitionsModuleOptions
): string =>
  options.importMode === "rootAbsolute"
    ? rootAbsoluteImportSpecifier(entry.moduleId)
    : relativeImportSpecifier(
        entry.moduleId,
        options.generatedFile ?? defaultGeneratedFileRouteDefinitionsFile
      );

const routeModuleExportName = (
  options: FileRouteDefinitionsModuleOptions
): string => {
  const exportName = options.routeModuleExportName ?? defaultRouteModuleExportName;
  if (!identifierPattern.test(exportName)) {
    throw new FileRouteDefinitionsModuleInvalidExportName({ exportName });
  }
  return exportName;
};

export const createFileRouteModuleReferences = (
  manifest: FileRouteManifest,
  options: FileRouteDefinitionsModuleOptions = {}
): readonly FileRouteModuleReference[] => {
  const importName = routeModuleExportName(options);
  return Array.from(manifest.entries, (entry) => ({
    entry,
    importName,
    identifier: asRouteIdentifier(entry),
    importSpecifier: routeModuleImportSpecifier(entry, options)
  }));
};

export const createFileRouteDefinitionsModule = (
  manifest: FileRouteManifest,
  options: FileRouteDefinitionsModuleOptions = {}
): string => {
  const references = createFileRouteModuleReferences(manifest, options);
  const routeImports = references.map(({ importName, identifier, importSpecifier }) =>
    `import { ${importName} as ${identifier} } from ${stringLiteral(importSpecifier)};`
  );
  const routePathChecks = references.map(({ entry, identifier }) =>
    `const ${identifier}_path: ${stringLiteral(entry.routePath)} = ${identifier}.path;`
  );
  const routeIdentifiers = references.map(({ identifier }) => identifier);
  const routeByIdEntries = references.map(({ identifier }) =>
    `  ${stringLiteral(identifier)}: ${identifier}`
  );
  const routeByPathEntries = references.map(({ entry, identifier }) =>
    `  ${stringLiteral(entry.routePath)}: ${identifier}`
  );
  const routeModules = JSON.stringify(manifest.modules, null, 2);
  const routeMetadata = JSON.stringify(describeFileRouteManifest(manifest), null, 2);

  return [
    'import type { Route } from "@effect-ui/core";',
    "",
    ...routeImports,
    ...(routeImports.length > 0 ? [""] : []),
    ...routePathChecks,
    ...(routePathChecks.length > 0 ? [""] : []),
    ...(routeIdentifiers.length > 0
      ? [`export { ${routeIdentifiers.join(", ")} };`, ""]
      : []),
    `export const routes = [${routeIdentifiers.join(", ")}] as const;`,
    "export const routeTree = routes;",
    "export const routeById = {",
    routeByIdEntries.join(",\n"),
    "} as const;",
    "export const routeByPath = {",
    routeByPathEntries.join(",\n"),
    "} as const;",
    "",
    `export const fileRouteModules = ${routeModules} as const;`,
    `export const fileRouteMetadata = ${routeMetadata} as const;`,
    "",
    "export type RouteTree = typeof routeTree;",
    "export type RouteById = typeof routeById;",
    "export type RouteByPath = typeof routeByPath;",
    "export type FileRoute = RouteTree[number];",
    "export type FileRouteId = keyof RouteById;",
    "export type FileRoutePath = keyof RouteByPath;",
    "export type FileRouteByPath = RouteByPath;",
    "export type FileRouteParamsById = { readonly [Id in FileRouteId]: Route.Params<RouteById[Id]> };",
    "export type FileRouteSearchById = { readonly [Id in FileRouteId]: Route.Search<RouteById[Id]> };",
    "export type FileRouteHrefOptionsById = { readonly [Id in FileRouteId]: Route.HrefOptions<RouteById[Id]> };",
    "export type FileRouteHrefOptions<Id extends FileRouteId> = FileRouteHrefOptionsById[Id];",
    "export type FileRouteParamsByPath = { readonly [Path in keyof FileRouteByPath]: Route.Params<FileRouteByPath[Path]> };",
    "export type FileRouteSearchByPath = { readonly [Path in keyof FileRouteByPath]: Route.Search<FileRouteByPath[Path]> };",
    "export type FileRouteHrefOptionsByPath = { readonly [Path in keyof FileRouteByPath]: Route.HrefOptions<FileRouteByPath[Path]> };",
    "export type FileRouteModules = typeof fileRouteModules;",
    "export type FileRouteMetadata = typeof fileRouteMetadata;",
    "export default routes;"
  ].join("\n");
};

export const createGeneratedFileRouteDefinitionsModule = (
  manifest: FileRouteManifest,
  options: GeneratedFileRouteDefinitionsModuleOptions = {}
): string => {
  const header = options.header ?? defaultGeneratedFileRouteDefinitionsHeader;
  return [
    header,
    "",
    createFileRouteDefinitionsModule(manifest, options),
    ""
  ].join("\n");
};
