import { Data } from "effect";
import {
  describeFileRouteManifest,
  type FileRouteManifest,
  type FileRouteManifestEntry,
  type FileRouteManifestModule
} from "./file-routes.js";

export interface FileRouteDefinitionsModuleOptions {
  readonly generatedFile?: string;
  readonly importMode?: "relative" | "rootAbsolute";
  readonly routeModuleExportName?: string;
}

export interface FileRouteModuleReference {
  readonly entry: FileRouteManifestEntry;
  readonly importName: string;
  readonly identifier: string;
  readonly importSpecifier: string;
}

export interface FileRouteCompanionModuleReference {
  readonly module: FileRouteManifestModule;
  readonly importName: string;
  readonly identifier: string;
  readonly importSpecifier: string;
}

export interface GeneratedFileRouteDefinitionsModuleOptions
  extends FileRouteDefinitionsModuleOptions {
  readonly header?: string;
}

export class FileRouteDefinitionsModuleInvalidIdentifier extends Data.TaggedError(
  "FileRouteDefinitionsModuleInvalidIdentifier"
)<{
  readonly routeId: string;
  readonly routePath: string;
}> {}

export class FileRouteDefinitionsModuleInvalidExportName extends Data.TaggedError(
  "FileRouteDefinitionsModuleInvalidExportName"
)<{
  readonly exportName: string;
}> {}

export type FileRouteDefinitionsModuleError =
  | FileRouteDefinitionsModuleInvalidIdentifier
  | FileRouteDefinitionsModuleInvalidExportName;

export const isFileRouteDefinitionsModuleError = (
  cause: unknown
): cause is FileRouteDefinitionsModuleError =>
  cause instanceof FileRouteDefinitionsModuleInvalidIdentifier ||
  cause instanceof FileRouteDefinitionsModuleInvalidExportName;

const defaultGeneratedFileRouteDefinitionsFile = "src/routeTree.gen.ts";
const defaultRouteModuleExportName = "Route";
export const defaultGeneratedFileRouteDefinitionsHeader =
  "// This file is generated by @effect-ui/start. Do not edit.";
const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const asRouteIdentifier = (entry: FileRouteManifestEntry): string => {
  const routeId = String(entry.routeId);
  if (!identifierPattern.test(routeId)) {
    throw new FileRouteDefinitionsModuleInvalidIdentifier({
      routeId,
      routePath: entry.routePath
    });
  }
  return routeId;
};

const companionModuleIdentifierPrefix = (
  module: FileRouteManifestModule
): string => {
  switch (module.kind) {
    case "Layout":
      return "layout";
    case "ErrorBoundary":
      return "errorBoundary";
    case "Metadata":
      return "metadata";
    case "Route":
      return "route";
  }
};

const asCompanionModuleIdentifier = (
  module: FileRouteManifestModule
): string => {
  const routeId = String(module.routeId);
  const identifier = `${companionModuleIdentifierPrefix(module)}_${routeId}`;
  if (!identifierPattern.test(identifier)) {
    throw new FileRouteDefinitionsModuleInvalidIdentifier({
      routeId,
      routePath: module.routePath
    });
  }
  return identifier;
};

const stringLiteral = (value: string): string => JSON.stringify(value);

const normalizePath = (path: string): string =>
  path
    .replace(/\\/g, "/")
    .replace(/\/+/g, "/")
    .replace(/\/$/, "");

const stripLeadingCurrentDirectory = (path: string): string =>
  path.startsWith("./") ? path.slice(2) : path;

const withRelativePrefix = (specifier: string): string =>
  specifier.startsWith(".") ? specifier : `./${specifier}`;

const isAbsolutePath = (path: string): boolean => path.startsWith("/");

const dirnamePath = (path: string): string => {
  const normalized = normalizePath(path);
  const slash = normalized.lastIndexOf("/");
  if (slash === -1) {
    return ".";
  }
  if (slash === 0) {
    return "/";
  }
  return normalized.slice(0, slash);
};

const extnamePath = (path: string): string => {
  const normalized = normalizePath(path);
  const slash = normalized.lastIndexOf("/");
  const dot = normalized.lastIndexOf(".");
  return dot > slash ? normalized.slice(dot) : "";
};

const splitRelativePath = (path: string): readonly string[] =>
  normalizePath(path)
    .replace(/^\/+/, "")
    .split("/")
    .filter((part) => part.length > 0 && part !== ".");

const relativePath = (from: string, target: string): string => {
  const fromParts = splitRelativePath(from);
  const targetParts = splitRelativePath(target);
  let common = 0;

  while (
    common < fromParts.length &&
    common < targetParts.length &&
    fromParts[common] === targetParts[common]
  ) {
    common++;
  }

  const parentParts = fromParts.slice(common).map(() => "..");
  const childParts = targetParts.slice(common);
  return [...parentParts, ...childParts].join("/") || ".";
};

const runtimeModulePath = (moduleId: string): string => {
  const normalized = normalizePath(moduleId).split(/[?#]/, 1)[0] ?? moduleId;
  const extension = extnamePath(normalized);
  switch (extension) {
    case ".ts":
    case ".tsx":
      return `${normalized.slice(0, -extension.length)}.js`;
    case ".mts":
      return `${normalized.slice(0, -extension.length)}.mjs`;
    case ".cts":
      return `${normalized.slice(0, -extension.length)}.cjs`;
    default:
      return normalized;
  }
};

const relativeImportSpecifier = (
  moduleId: string,
  generatedFile: string
): string => {
  const source = runtimeModulePath(moduleId);
  const fromDirectory = dirnamePath(stripLeadingCurrentDirectory(normalizePath(generatedFile)));
  const target = stripLeadingCurrentDirectory(source);
  const specifier = isAbsolutePath(fromDirectory) === isAbsolutePath(target)
    ? relativePath(fromDirectory, target)
    : relativePath(fromDirectory.replace(/^\/+/, ""), target.replace(/^\/+/, ""));

  return withRelativePrefix(normalizePath(specifier));
};

const rootAbsoluteImportSpecifier = (moduleId: string): string => {
  const source = runtimeModulePath(moduleId);
  return source.startsWith("/")
    ? source
    : `/${stripLeadingCurrentDirectory(source)}`;
};

const routeModuleImportSpecifier = (
  entry: Pick<FileRouteManifestEntry | FileRouteManifestModule, "moduleId">,
  options: FileRouteDefinitionsModuleOptions
): string =>
  options.importMode === "rootAbsolute"
    ? rootAbsoluteImportSpecifier(entry.moduleId)
    : relativeImportSpecifier(
        entry.moduleId,
        options.generatedFile ?? defaultGeneratedFileRouteDefinitionsFile
      );

const routeModuleExportName = (
  options: FileRouteDefinitionsModuleOptions
): string => {
  const exportName = options.routeModuleExportName ?? defaultRouteModuleExportName;
  if (!identifierPattern.test(exportName)) {
    throw new FileRouteDefinitionsModuleInvalidExportName({ exportName });
  }
  return exportName;
};

export const createFileRouteModuleReferences = (
  manifest: FileRouteManifest,
  options: FileRouteDefinitionsModuleOptions = {}
): readonly FileRouteModuleReference[] => {
  const importName = routeModuleExportName(options);
  return Array.from(manifest.entries, (entry) => ({
    entry,
    importName,
    identifier: asRouteIdentifier(entry),
    importSpecifier: routeModuleImportSpecifier(entry, options)
  }));
};

const uniqueCompanionModules = (
  manifest: FileRouteManifest
): readonly FileRouteManifestModule[] => {
  const metadata = describeFileRouteManifest(manifest);
  const referencedModuleIds = new Set(
    metadata.flatMap((entry) => [
      ...entry.layouts,
      ...(entry.errorBoundary === undefined ? [] : [entry.errorBoundary]),
      ...entry.metadataModules
    ]).map((module) => module.moduleId)
  );
  return manifest.modules.filter((module) =>
    module.kind !== "Route" && referencedModuleIds.has(module.moduleId)
  );
};

export const createFileRouteCompanionModuleReferences = (
  manifest: FileRouteManifest,
  options: FileRouteDefinitionsModuleOptions = {}
): readonly FileRouteCompanionModuleReference[] =>
  uniqueCompanionModules(manifest).map((module) => {
    if (!identifierPattern.test(module.exportName)) {
      throw new FileRouteDefinitionsModuleInvalidExportName({
        exportName: module.exportName
      });
    }

    return {
      module,
      importName: module.exportName,
      identifier: asCompanionModuleIdentifier(module),
      importSpecifier: routeModuleImportSpecifier(module, options)
    };
  });

export const createFileRouteDefinitionsModule = (
  manifest: FileRouteManifest,
  options: FileRouteDefinitionsModuleOptions = {}
): string => {
  const references = createFileRouteModuleReferences(manifest, options);
  const companionReferences = createFileRouteCompanionModuleReferences(manifest, options);
  const companionReferenceByModuleId = new Map(
    companionReferences.map((reference) => [reference.module.moduleId, reference])
  );
  const routeImports = references.map(({ importName, identifier, importSpecifier }) =>
    `import { ${importName} as ${identifier} } from ${stringLiteral(importSpecifier)};`
  );
  const companionImports = companionReferences.map(({ importName, identifier, importSpecifier }) =>
    `import { ${importName} as ${identifier} } from ${stringLiteral(importSpecifier)};`
  );
  const routePathChecks = references.map(({ entry, identifier }) =>
    `const ${identifier}_path: ${stringLiteral(entry.routePath)} = ${identifier}.path;`
  );
  const routeIdentifiers = references.map(({ identifier }) => identifier);
  const routeByIdEntries = references.map(({ identifier }) =>
    `  ${stringLiteral(identifier)}: ${identifier}`
  );
  const routeByPathEntries = references.map(({ entry, identifier }) =>
    `  ${stringLiteral(entry.routePath)}: ${identifier}`
  );
  const routeIdByPathEntries = references.map(({ entry, identifier }) =>
    `  ${stringLiteral(entry.routePath)}: ${stringLiteral(identifier)}`
  );
  const routeModules = JSON.stringify(manifest.modules, null, 2);
  const describedRouteMetadata = describeFileRouteManifest(manifest);
  const routeMetadata = JSON.stringify(describedRouteMetadata, null, 2);
  const identifierForCompanionModule = (module: FileRouteManifestModule): string => {
    const reference = companionReferenceByModuleId.get(module.moduleId);
    if (!reference) {
      throw new FileRouteDefinitionsModuleInvalidIdentifier({
        routeId: String(module.routeId),
        routePath: module.routePath
      });
    }
    return reference.identifier;
  };
  const layoutEntries = describedRouteMetadata.map((entry) =>
    `  ${stringLiteral(String(entry.routeId))}: [${entry.layouts.map(identifierForCompanionModule).join(", ")}]`
  );
  const errorBoundaryEntries = describedRouteMetadata.flatMap((entry) =>
    entry.errorBoundary === undefined
      ? []
      : [
          `  ${stringLiteral(String(entry.routeId))}: ${identifierForCompanionModule(entry.errorBoundary)}`
        ]
  );
  const metadataEntries = describedRouteMetadata.map((entry) =>
    `  ${stringLiteral(String(entry.routeId))}: [${entry.metadataModules.map(identifierForCompanionModule).join(", ")}]`
  );

  return [
    'import { Route } from "@effect-ui/core";',
    "",
    ...routeImports,
    ...companionImports,
    ...(routeImports.length + companionImports.length > 0 ? [""] : []),
    ...routePathChecks,
    ...(routePathChecks.length > 0 ? [""] : []),
    ...(routeIdentifiers.length > 0
      ? [`export { ${routeIdentifiers.join(", ")} };`, ""]
      : []),
    "/** Ordered app-specific route definitions discovered from Start file routes. */",
    `export const routes = [${routeIdentifiers.join(", ")}] as const;`,
    "/** Alias for `routes`, kept for router-style naming and generated-file ergonomics. */",
    "export const routeTree = routes;",
    "/** Map from generated route id to the exact route definition for that file route. */",
    "export const routeById = {",
    routeByIdEntries.join(",\n"),
    "} as const;",
    "/** Map from route path pattern to the exact route definition for that file route. */",
    "export const routeByPath = {",
    routeByPathEntries.join(",\n"),
    "} as const;",
    "/** Map from route path pattern to generated route id. */",
    "export const routeIdByPath = {",
    routeIdByPathEntries.join(",\n"),
    "} as const;",
    "/** Builds a typed href for a generated route id. */",
    "export const hrefById = <Id extends RouteId>(",
    "  id: Id,",
    "  ...args: Route.HrefArgs<RouteById[Id]>",
    "): string => Route.href(routeById[id], ...args);",
    "/** Builds a typed href for a generated route path pattern. */",
    "export const hrefByPath = <Path extends RoutePath>(",
    "  path: Path,",
    "  ...args: Route.HrefArgs<RouteByPath[Path]>",
    "): string => Route.href(routeByPath[path], ...args);",
    "",
    "/** Layout modules that wrap each generated route, ordered from root to leaf. */",
    "export const fileRouteLayoutsById = {",
    layoutEntries.join(",\n"),
    "} as const;",
    "/** Nearest error boundary module for each generated route, when one exists. */",
    "export const fileRouteErrorBoundaryById = {",
    errorBoundaryEntries.join(",\n"),
    "} as const;",
    "/** Metadata modules scoped to each generated route, ordered from root to leaf. */",
    "export const fileRouteMetadataById = {",
    metadataEntries.join(",\n"),
    "} as const;",
    "/** Returns layout modules for a generated route id. */",
    "export const layoutsById = <Id extends RouteId>(",
    "  id: Id",
    "): FileRouteLayouts<Id> => fileRouteLayoutsById[id];",
    "/** Returns layout modules for a generated route path pattern. */",
    "export const layoutsByPath = <Path extends RoutePath>(",
    "  path: Path",
    "): FileRouteLayouts<RouteIdByPath[Path]> => layoutsById(routeIdByPath[path]);",
    "/** Returns the nearest error boundary module for a generated route id, when one exists. */",
    "export const errorBoundaryById = <Id extends RouteId>(",
    "  id: Id",
    "): FileRouteErrorBoundary<Id> =>",
    "  (fileRouteErrorBoundaryById as Partial<Record<RouteId, unknown>>)[id] as FileRouteErrorBoundary<Id>;",
    "/** Returns the nearest error boundary module for a generated route path pattern, when one exists. */",
    "export const errorBoundaryByPath = <Path extends RoutePath>(",
    "  path: Path",
    "): FileRouteErrorBoundary<RouteIdByPath[Path]> => errorBoundaryById(routeIdByPath[path]);",
    "/** Returns metadata modules for a generated route id. */",
    "export const metadataById = <Id extends RouteId>(",
    "  id: Id",
    "): FileRouteMetadataModules<Id> => fileRouteMetadataById[id];",
    "/** Returns metadata modules for a generated route path pattern. */",
    "export const metadataByPath = <Path extends RoutePath>(",
    "  path: Path",
    "): FileRouteMetadataModules<RouteIdByPath[Path]> => metadataById(routeIdByPath[path]);",
    "",
    "/** Route, layout, error boundary, and metadata modules discovered by Start. */",
    `export const fileRouteModules = ${routeModules} as const;`,
    "/** Parent, layout, error boundary, and metadata relationships for each generated route. */",
    `export const fileRouteMetadata = ${routeMetadata} as const;`,
    "",
    "/** Tuple type for the generated app-specific route tree. */",
    "export type RouteTree = typeof routeTree;",
    "/** Map type keyed by generated route id. */",
    "export type RouteById = typeof routeById;",
    "/** Map type keyed by route path pattern. */",
    "export type RouteByPath = typeof routeByPath;",
    "/** Map type from route path pattern to generated route id. */",
    "export type RouteIdByPath = typeof routeIdByPath;",
    "/** Union of every generated route definition. */",
    "export type FileRoute = RouteTree[number];",
    "/** Union of generated route ids such as `route_projects_$id`. */",
    "export type FileRouteId = keyof RouteById;",
    "/** Union of generated route path patterns such as `/projects/:id`. */",
    "export type FileRoutePath = keyof RouteByPath;",
    "/** Route path lookup map preserved for path-keyed helper types. */",
    "export type FileRouteByPath = RouteByPath;",
    "/** Params for each generated route id. */",
    "export type FileRouteParamsById = { readonly [Id in FileRouteId]: Route.Params<RouteById[Id]> };",
    "/** Search values for each generated route id. */",
    "export type FileRouteSearchById = { readonly [Id in FileRouteId]: Route.Search<RouteById[Id]> };",
    "/** Href options for each generated route id. */",
    "export type FileRouteHrefOptionsById = { readonly [Id in FileRouteId]: Route.HrefOptions<RouteById[Id]> };",
    "/** Href options for one generated route id. */",
    "export type FileRouteHrefOptions<Id extends FileRouteId> = FileRouteHrefOptionsById[Id];",
    "/** Href arguments for each generated route id. */",
    "export type FileRouteHrefArgsById = { readonly [Id in FileRouteId]: Route.HrefArgs<RouteById[Id]> };",
    "/** Href arguments for one generated route id. */",
    "export type FileRouteHrefArgs<Id extends FileRouteId> = FileRouteHrefArgsById[Id];",
    "/** Params for each generated route path pattern. */",
    "export type FileRouteParamsByPath = { readonly [Path in keyof FileRouteByPath]: Route.Params<FileRouteByPath[Path]> };",
    "/** Search values for each generated route path pattern. */",
    "export type FileRouteSearchByPath = { readonly [Path in keyof FileRouteByPath]: Route.Search<FileRouteByPath[Path]> };",
    "/** Href options for each generated route path pattern. */",
    "export type FileRouteHrefOptionsByPath = { readonly [Path in keyof FileRouteByPath]: Route.HrefOptions<FileRouteByPath[Path]> };",
    "/** Href arguments for each generated route path pattern. */",
    "export type FileRouteHrefArgsByPath = { readonly [Path in keyof FileRouteByPath]: Route.HrefArgs<FileRouteByPath[Path]> };",
    "/** Route match narrowed to one generated route path pattern. */",
    "export type FileRouteMatch<Path extends FileRoutePath> = Route.Match<FileRouteByPath[Path]>;",
    "/** Layout modules keyed by generated route id. */",
    "export type FileRouteLayoutsById = typeof fileRouteLayoutsById;",
    "/** Error boundary modules keyed by generated route id when present. */",
    "export type FileRouteErrorBoundaryById = typeof fileRouteErrorBoundaryById;",
    "/** Metadata modules keyed by generated route id. */",
    "export type FileRouteMetadataById = typeof fileRouteMetadataById;",
    "/** Layout modules for one generated route id. */",
    "export type FileRouteLayouts<Id extends FileRouteId> = FileRouteLayoutsById[Id];",
    "/** Error boundary module for one generated route id, or undefined when none is scoped. */",
    "export type FileRouteErrorBoundary<Id extends FileRouteId> = Id extends keyof FileRouteErrorBoundaryById ? FileRouteErrorBoundaryById[Id] : undefined;",
    "/** Metadata modules for one generated route id. */",
    "export type FileRouteMetadataModules<Id extends FileRouteId> = FileRouteMetadataById[Id];",
    "/** Friendly alias for the generated route id union. */",
    "export type RouteId = FileRouteId;",
    "/** Friendly alias for the generated route path union. */",
    "export type RoutePath = FileRoutePath;",
    "/** Friendly alias for params keyed by generated route id. */",
    "export type ParamsById = FileRouteParamsById;",
    "/** Friendly alias for search values keyed by generated route id. */",
    "export type SearchById = FileRouteSearchById;",
    "/** Friendly alias for href options keyed by generated route id. */",
    "export type HrefById = FileRouteHrefOptionsById;",
    "/** Friendly alias for href options for one generated route id. */",
    "export type Href<Id extends RouteId> = FileRouteHrefOptions<Id>;",
    "/** Friendly alias for href arguments keyed by generated route id. */",
    "export type HrefArgsById = FileRouteHrefArgsById;",
    "/** Friendly alias for href arguments for one generated route id. */",
    "export type HrefArgs<Id extends RouteId> = FileRouteHrefArgs<Id>;",
    "/** Friendly alias for params keyed by generated route path. */",
    "export type ParamsByPath = FileRouteParamsByPath;",
    "/** Friendly alias for search values keyed by generated route path. */",
    "export type SearchByPath = FileRouteSearchByPath;",
    "/** Friendly alias for href options keyed by generated route path. */",
    "export type HrefByPath = FileRouteHrefOptionsByPath;",
    "/** Friendly alias for href arguments keyed by generated route path. */",
    "export type HrefArgsByPath = FileRouteHrefArgsByPath;",
    "/** Friendly alias for route matches narrowed by generated route path. */",
    "export type Match<Path extends RoutePath> = FileRouteMatch<Path>;",
    "/** Narrows a broad route match to one generated route path pattern. */",
    "export const isRoutePathMatch = <Path extends FileRoutePath>(",
    "  path: Path,",
    "  match: Route.Match<FileRoute> | undefined",
    "): match is FileRouteMatch<Path> => match?.route.path === path;",
    "/** Static metadata for all file-route modules discovered by Start. */",
    "export type FileRouteModules = typeof fileRouteModules;",
    "/** Static parent/layout/error/metadata relationships for generated routes. */",
    "export type FileRouteMetadata = typeof fileRouteMetadata;",
    "/** Default generated route tree export for router-style imports. */",
    "export default routes;"
  ].join("\n");
};

export const createGeneratedFileRouteDefinitionsModule = (
  manifest: FileRouteManifest,
  options: GeneratedFileRouteDefinitionsModuleOptions = {}
): string => {
  const header = options.header ?? defaultGeneratedFileRouteDefinitionsHeader;
  return [
    header,
    "",
    createFileRouteDefinitionsModule(manifest, options),
    ""
  ].join("\n");
};
