import {
  runWithRuntime,
  toEffect,
  type EffectInput,
  type EffectUiRuntime,
  type ResourceStoreDiagnosticsSnapshot,
  type Route
} from "@effect-ui/core";
import type { AnyCollection } from "@effect-ui/db";
import { Cause, Clock, Effect, Exit, Metric, Redacted } from "effect";
import {
  makeStartRequestIdEffect,
  startRequestIdHeader,
  startTraceparentHeader
} from "./rpc.js";
import {
  resolveStartTransportEndpoints,
  type StartTransportEndpointSource
} from "./start-transport-endpoints.js";

/** Request transport classification used by Start request traces and metrics. */
export type StartRequestTraceTransport = "ssr" | "rpc" | "action" | "unknown";

/** Final outcome recorded for a Start request trace. */
export type StartRequestTraceStatus = "success" | "failure" | "cancelled";

/** Failure category used by diagnostics without exposing raw causes. */
export type StartRequestTraceFailureKind =
  | "domain"
  | "validation"
  | "protocol"
  | "transport"
  | "defect"
  | "interruption";

/** Lifecycle state for streamed SSR response traces. */
export type StartRequestTraceStreamState = "open" | "closed" | "cancelled" | "errored";

/** Lifecycle state for the request runtime fiber recorded in traces. */
export type StartRequestTraceFiberStatus = "running" | "done" | "interrupted" | "failed";

/** Redacted or safe header value captured for request/response diagnostics. */
export interface StartRequestTraceHeader {
  /** Lowercase or platform-preserved header name. */
  readonly name: string;
  /** Header value, redacted for sensitive header names. */
  readonly value: string;
}

/** Redacted request cookie captured for diagnostics. */
export interface StartRequestTraceCookie {
  /** Decoded cookie name. */
  readonly name: string;
  /** Redacted decoded cookie value. */
  readonly value: string;
}

/** Request snapshot at the boundary of a Start request handler. */
export interface StartRequestTraceRequest {
  /** Correlation id generated by Start or read from the incoming request header. */
  readonly id?: string;
  /** Incoming W3C traceparent header when present. */
  readonly traceparent?: string;
  /** HTTP request method. */
  readonly method: string;
  /** Full request URL. */
  readonly url: string;
  /** URL pathname used for request metrics. */
  readonly path: string;
  /** Start transport that handled the request. */
  readonly transport: StartRequestTraceTransport;
  /** Safe request headers included when any were captured. */
  readonly headers?: ReadonlyArray<StartRequestTraceHeader>;
  /** Redacted request cookies included when any were present. */
  readonly cookies?: ReadonlyArray<StartRequestTraceCookie>;
}

/** Response snapshot emitted with a completed Start request trace. */
export interface StartRequestTraceResponse {
  /** Final HTTP status. */
  readonly status: number;
  /** Final HTTP status text when the platform response supplied one. */
  readonly statusText?: string;
  /** Safe response headers included when any were captured. */
  readonly headers?: ReadonlyArray<StartRequestTraceHeader>;
  /** Count of Set-Cookie headers when the platform exposes them. */
  readonly setCookieCount?: number;
}

/** Resource touched during route preload or request handling. */
export interface StartRequestTraceResource {
  /** Stable Resource ref key. */
  readonly key: string;
  /** Resource family name. */
  readonly family: string;
  /** Resource input when available for diagnostics. */
  readonly input?: unknown;
  /** Current Resource state tag when it can be observed safely. */
  readonly state?: string;
}

/** Collection included in route preload, registration, or dehydration diagnostics. */
export interface StartRequestTraceCollection {
  /** Collection definition name. */
  readonly name: string;
  /** Current collection state tag when it can be observed safely. */
  readonly state?: string;
}

/** Server function call summary recorded for RPC request traces. */
export interface StartRequestTraceServerFunction {
  /** Registered server function name. */
  readonly name: string;
  /** Outcome for this server function call when known. */
  readonly status?: StartRequestTraceStatus;
  /** Failure kind for this server function call when it failed. */
  readonly failureKind?: StartRequestTraceFailureKind;
}

/** Start action call summary recorded for action request traces. */
export interface StartRequestTraceAction {
  /** Registered action name. */
  readonly name: string;
  /** Action state or result tag when known. */
  readonly state?: string;
  /** Failure kind for this action call when it failed. */
  readonly failureKind?: StartRequestTraceFailureKind;
  /** Invalidation indexes returned by the action response payload. */
  readonly invalidationIndexes?: ReadonlyArray<number>;
}

/** Request runtime fiber summary emitted with every trace. */
export interface StartRequestTraceFiber {
  /** Logical fiber name. */
  readonly name: string;
  /** Final fiber state. */
  readonly status: StartRequestTraceFiberStatus;
}

/** Stream lifecycle summary for streamed SSR responses. */
export interface StartRequestTraceStream {
  /** Logical stream name. */
  readonly name: string;
  /** Final stream lifecycle state. */
  readonly state: StartRequestTraceStreamState;
  /** Number of chunks successfully written before close/failure. */
  readonly chunkCount?: number;
  /** Stream phase that failed when a streamed response errored. */
  readonly failurePhase?: "Shell" | "Chunk" | "Tail";
}

/** Resource Store diagnostics snapshot captured during request runtime teardown. */
export interface StartRequestTraceTeardownSnapshot extends ResourceStoreDiagnosticsSnapshot {}

/** Request runtime teardown summary captured before and after disposal. */
export interface StartRequestTraceTeardown {
  /** Whether the request runtime disposal path completed. */
  readonly runtimeDisposed: boolean;
  /** Human-readable teardown reason such as normal completion or stream close. */
  readonly reason?: string;
  /** Legacy single timestamp retained for compatibility with older trace consumers. */
  readonly at?: number;
  /** Timestamp before request runtime disposal begins. */
  readonly startedAt?: number;
  /** Timestamp after request runtime disposal completes. */
  readonly completedAt?: number;
  /** Disposal duration in milliseconds when both timestamps are available. */
  readonly durationMillis?: number;
  /** Resource Store diagnostics before disposal. */
  readonly beforeDispose?: StartRequestTraceTeardownSnapshot;
  /** Resource Store diagnostics after disposal. */
  readonly afterDispose?: StartRequestTraceTeardownSnapshot;
}

/** Complete best-effort observability record emitted for a handled Start request. */
export interface StartRequestTrace {
  /** Request boundary snapshot. */
  readonly request: StartRequestTraceRequest;
  /** Response boundary snapshot when a response was produced. */
  readonly response?: StartRequestTraceResponse;
  /** Request-scoped services provided by Start. */
  readonly services: ReadonlyArray<string>;
  /** Route planning summary for SSR requests. */
  readonly routePlan?: StartRequestTraceRoutePlan;
  /** Resources touched during the request. */
  readonly resources: ReadonlyArray<StartRequestTraceResource>;
  /** Collections touched during route preload, registration, or dehydration. */
  readonly collections: ReadonlyArray<StartRequestTraceCollection>;
  /** Server function calls observed during the request. */
  readonly serverFunctions: ReadonlyArray<StartRequestTraceServerFunction>;
  /** Start action calls observed during the request. */
  readonly actions: ReadonlyArray<StartRequestTraceAction>;
  /** Request runtime fibers observed during the request. */
  readonly fibers: ReadonlyArray<StartRequestTraceFiber>;
  /** Stream lifecycle records observed during the request. */
  readonly streams: ReadonlyArray<StartRequestTraceStream>;
  /** Final request outcome. */
  readonly status: StartRequestTraceStatus;
  /** Failure kind when the request failed or was interrupted. */
  readonly failureKind?: StartRequestTraceFailureKind;
  /** Request runtime teardown diagnostics. */
  readonly teardown?: StartRequestTraceTeardown;
}

/** Route preload and hydration summary attached to SSR request traces. */
export interface StartRequestTraceRoutePlan {
  /** Whether a route matched the request href. */
  readonly _tag: "Matched" | "NotFound";
  /** Href passed through route planning. */
  readonly href: string;
  /** Matched route details, or undefined when no route matched. */
  readonly match:
    | {
        /** Matched route path template. */
        readonly path: string;
        /** Matched href including path and search. */
        readonly href: string;
        /** Decoded route params. */
        readonly params: unknown;
        /** Decoded route search values. */
        readonly search: unknown;
      }
    | undefined;
  /** Resource refs collected while route preload ran. */
  readonly resources: ReadonlyArray<{
    /** Stable Resource ref key. */
    readonly key: string;
    /** Resource family name. */
    readonly family: string;
    /** Resource input used to build the ref. */
    readonly input: unknown;
  }>;
  /** Hydration payload summary produced after preload. */
  readonly hydration: {
    /** Number of Resource snapshots in the hydration payload. */
    readonly resourceCount: number;
    /** Resource keys included in the hydration payload. */
    readonly resourceKeys?: ReadonlyArray<string>;
  };
}

/** Mutable request-local facts accumulated while a Start handler runs. */
export interface StartRequestTraceFacts {
  /** Request correlation id. */
  readonly requestId: string;
  /** Transport selected for this request. */
  readonly transport: StartRequestTraceTransport;
  /** Handler start timestamp. */
  readonly startedAt: number;
  /** Route plan recorded by the SSR path. */
  routePlan?: StartRequestTraceRoutePlan;
  /** Collection facts accumulated during preload/dehydration. */
  collections: StartRequestTraceCollection[];
  /** Server function facts accumulated by RPC handling. */
  serverFunctions: StartRequestTraceServerFunction[];
  /** Action facts accumulated by action handling. */
  actions: StartRequestTraceAction[];
  /** Failure classification set by the failing path. */
  failureKind?: StartRequestTraceFailureKind;
}

/** Collection groups used to build request trace preload diagnostics. */
export interface StartCollectionPreloadTraceInput {
  /** Collections touched by route resource/preload execution. */
  readonly routeTouchedCollections: ReadonlyArray<AnyCollection>;
  /** Collections declared statically by the matched route. */
  readonly routeDeclaredCollections: ReadonlyArray<AnyCollection>;
  /** Collections registered with the Start app/runtime. */
  readonly registeredCollections: ReadonlyArray<AnyCollection>;
  /** Collections included in the dehydrated payload. */
  readonly dehydratedCollections: ReadonlyArray<AnyCollection>;
}

/** Best-effort request diagnostics hook. Failures from the hook are ignored. */
export type StartRequestTraceHandler = (trace: StartRequestTrace) => EffectInput<void, never, never>;

/** Invokes Start best-effort EffectInput callbacks without leaking callback defects. */
export const invokeStartEffectInputCallbackEffect = <Input>(
  callback: ((input: Input) => EffectInput<void, never, never>) | undefined,
  input: Input
): Effect.Effect<void> =>
  callback === undefined
    ? Effect.void
    : Effect.suspend(() => toEffect(callback(input))).pipe(
        Effect.catchCause(() => Effect.void)
      );

/** Effect Metric counter for total Start requests by transport, method, and path. */
export const startRequestCountMetric = Metric.counter("effect_ui_start_requests_total", {
  description: "Total Start requests handled by transport, method, and path.",
  incremental: true
});

/** Effect Metric timer for Start request duration by transport, method, and path. */
export const startRequestDurationMetric = Metric.timer("effect_ui_start_request_duration", {
  description: "Start request handler duration by transport, method, and path."
});

/** Effect Metric frequency for Start request outcomes by transport, method, path, and status. */
export const startRequestStatusMetric = Metric.frequency("effect_ui_start_request_status", {
  description: "Start request outcomes by transport, method, path, and status."
});

export const startRequestTraceTransport = (
  request: Request,
  endpoints?: StartTransportEndpointSource
): StartRequestTraceTransport => {
  const pathname = new URL(request.url).pathname;
  const resolved = resolveStartTransportEndpoints(endpoints);
  return pathname === resolved.rpcPath
    ? "rpc"
    : pathname === resolved.actionPath
      ? "action"
      : "ssr";
};

const redactedTraceValue = (value: string): string =>
  String(Redacted.make(value));

const sensitiveTraceHeaderNames = new Set([
  "authorization",
  "cookie",
  "proxy-authorization",
  "set-cookie",
  "x-api-key",
  "x-auth-token"
]);

const traceHeaderValue = (name: string, value: string): string =>
  sensitiveTraceHeaderNames.has(name.toLowerCase())
    ? redactedTraceValue(value)
    : value;

const traceHeaders = (headers: Headers): ReadonlyArray<StartRequestTraceHeader> => {
  const out: StartRequestTraceHeader[] = [];
  headers.forEach((value, name) => {
    out.push({ name, value: traceHeaderValue(name, value) });
  });
  return out.sort((left, right) => {
    const byName = left.name.localeCompare(right.name);
    return byName === 0 ? left.value.localeCompare(right.value) : byName;
  });
};

const decodeTraceCookiePart = (value: string): string => {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
};

const traceCookies = (headers: Headers): ReadonlyArray<StartRequestTraceCookie> => {
  const cookie = headers.get("cookie");
  if (!cookie) {
    return [];
  }

  return cookie
    .split(";")
    .flatMap((part) => {
      const [rawName, ...rawValue] = part.trim().split("=");
      return rawName
        ? [
            {
              name: decodeTraceCookiePart(rawName),
              value: redactedTraceValue(decodeTraceCookiePart(rawValue.join("=")))
            }
          ]
        : [];
    })
    .sort((left, right) => left.name.localeCompare(right.name));
};

const startTraceSetCookieCount = (headers: Headers): number => {
  const getSetCookie = (headers as Headers & { readonly getSetCookie?: unknown }).getSetCookie;
  if (typeof getSetCookie !== "function") {
    return 0;
  }

  const cookies = getSetCookie.call(headers);
  return Array.isArray(cookies) ? cookies.length : 0;
};

const traceResponse = (response: Response): StartRequestTraceResponse => {
  const headers = traceHeaders(response.headers);
  const setCookieCount = startTraceSetCookieCount(response.headers);
  return {
    status: response.status,
    ...(response.statusText === "" ? {} : { statusText: response.statusText }),
    ...(headers.length === 0 ? {} : { headers }),
    ...(setCookieCount === 0 ? {} : { setCookieCount })
  };
};

const traceRequest = (
  request: Request,
  facts: StartRequestTraceFacts
): StartRequestTraceRequest => {
  const url = new URL(request.url);
  const headers = traceHeaders(request.headers);
  const cookies = traceCookies(request.headers);
  const traceparent = request.headers.get(startTraceparentHeader)?.trim() || undefined;
  return {
    id: facts.requestId,
    ...(traceparent === undefined ? {} : { traceparent }),
    method: request.method,
    url: request.url,
    path: url.pathname,
    transport: facts.transport,
    ...(headers.length === 0 ? {} : { headers }),
    ...(cookies.length === 0 ? {} : { cookies })
  };
};

const requestPath = (request: Request): string =>
  new URL(request.url).pathname;

const requestMetricAttributes = (
  request: Request,
  facts: StartRequestTraceFacts
): Record<string, string> => ({
  transport: facts.transport,
  method: request.method,
  path: requestPath(request)
});

const requestLogAnnotations = (
  request: Request,
  facts: StartRequestTraceFacts
): Record<string, string> => ({
  "effect-ui.request.id": facts.requestId,
  "effect-ui.request.transport": facts.transport,
  "http.request.method": request.method,
  "url.path": requestPath(request)
});

const requestSpanAttributes = (
  request: Request,
  facts: StartRequestTraceFacts
): Record<string, unknown> => {
  const traceparent = request.headers.get(startTraceparentHeader)?.trim() || undefined;
  return {
    ...requestLogAnnotations(request, facts),
    ...(traceparent === undefined ? {} : { traceparent })
  };
};

const exitStatus = <A, E>(exit: Exit.Exit<A, E>): StartRequestTraceStatus =>
  Exit.isSuccess(exit)
    ? "success"
    : exit.cause.reasons.some(Cause.isInterruptReason)
      ? "cancelled"
      : "failure";

export const withStartRequestObservability = <A, E, R>(
  request: Request,
  facts: StartRequestTraceFacts,
  effect: Effect.Effect<A, E, R>
): Effect.Effect<A, E, R> => {
  const attributes = requestMetricAttributes(request, facts);
  const observed = Effect.gen(function* () {
    yield* Metric.update(Metric.withAttributes(startRequestCountMetric, attributes), 1);
    const exit = yield* Effect.exit(effect);
    const status = exitStatus(exit);
    yield* Metric.update(
      Metric.withAttributes(startRequestStatusMetric, {
        ...attributes,
        status
      }),
      status
    );
    if (Exit.isSuccess(exit)) {
      return exit.value;
    }
    return yield* Effect.failCause(exit.cause);
  });

  return observed.pipe(
    Effect.trackDuration(Metric.withAttributes(startRequestDurationMetric, attributes)),
    Effect.annotateLogs(requestLogAnnotations(request, facts)),
    Effect.withSpan("effect-ui.start.request", {
      kind: "server",
      attributes: requestSpanAttributes(request, facts)
    })
  );
};

export const withStartRpcObservability = <A, E, R>(
  name: string,
  effect: Effect.Effect<A, E, R>
): Effect.Effect<A, E, R> =>
  effect.pipe(
    Effect.annotateLogs("effect-ui.rpc.name", name),
    Effect.withSpan("effect-ui.start.rpc", {
      kind: "server",
      attributes: {
        "effect-ui.rpc.name": name
      }
    })
  );

export const withStartActionObservability = <A, E, R>(
  name: string,
  effect: Effect.Effect<A, E, R>
): Effect.Effect<A, E, R> =>
  effect.pipe(
    Effect.annotateLogs("effect-ui.action.name", name),
    Effect.withSpan("effect-ui.start.action", {
      kind: "server",
      attributes: {
        "effect-ui.action.name": name
      }
    })
  );

const traceResourceRefs = (
  refs: ReadonlyArray<{ readonly key: string; readonly family: { readonly options: { readonly name: string } }; readonly input: unknown }>
): ReadonlyArray<StartRequestTraceResource> =>
  refs.map((ref) => ({
    key: ref.key,
    family: ref.family.options.name,
    input: ref.input
  }));

export const traceRoutePlan = (
  plan: Route.NavigationPlan
): StartRequestTraceRoutePlan => ({
  _tag: plan._tag,
  href: plan.href,
  match: plan.match
    ? {
        path: plan.match.route.path,
        href: plan.match.href,
        params: plan.match.params,
        search: plan.match.search
      }
    : undefined,
  resources: traceResourceRefs(plan.refs).map((resource) => ({
    key: resource.key,
    family: resource.family,
    input: resource.input
  })),
  hydration: {
    resourceCount: plan.resources.resources.length,
    resourceKeys: plan.resources.resources.map((resource) => resource.key)
  }
});

const uniqueCollections = (
  collections: Iterable<AnyCollection>
): ReadonlyArray<AnyCollection> => {
  const names = new Set<string>();
  const out: Array<AnyCollection> = [];
  for (const collection of collections) {
    if (!names.has(collection.name)) {
      names.add(collection.name);
      out.push(collection);
    }
  }
  return out;
};

const collectionTraceState = <RuntimeServices, RuntimeError>(
  runtime: EffectUiRuntime<RuntimeServices, RuntimeError>,
  collection: AnyCollection
): string | undefined => {
  try {
    return runWithRuntime(runtime, () => collection.state().get()._tag);
  } catch {
    return undefined;
  }
};

export const traceCollectionPreload = <RuntimeServices, RuntimeError>(
  runtime: EffectUiRuntime<RuntimeServices, RuntimeError>,
  collectionPreload: StartCollectionPreloadTraceInput
): ReadonlyArray<StartRequestTraceCollection> =>
  uniqueCollections([
    ...collectionPreload.routeTouchedCollections,
    ...collectionPreload.routeDeclaredCollections,
    ...collectionPreload.registeredCollections,
    ...collectionPreload.dehydratedCollections
  ])
    .map((collection) => {
      const state = collectionTraceState(runtime, collection);
      return {
        name: collection.name,
        ...(state === undefined ? {} : { state })
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name));

export const startRequestTraceFactsEffect = (
  request: Request,
  endpoints?: StartTransportEndpointSource
): Effect.Effect<StartRequestTraceFacts> =>
  Effect.gen(function* () {
    const incomingRequestId = request.headers.get(startRequestIdHeader)?.trim();
    const startedAt = yield* Clock.currentTimeMillis;
    return {
      requestId: incomingRequestId && !/[\r\n]/.test(incomingRequestId)
        ? incomingRequestId
        : yield* makeStartRequestIdEffect,
      transport: startRequestTraceTransport(request, endpoints),
      startedAt,
      collections: [],
      serverFunctions: [],
      actions: []
    };
  });

export const emitStartRequestTraceEffect = (
  handler: StartRequestTraceHandler | undefined,
  trace: StartRequestTrace
): Effect.Effect<void> =>
  invokeStartEffectInputCallbackEffect(handler, trace);

export const buildStartRequestTrace = (
  request: Request,
  facts: StartRequestTraceFacts,
  status: StartRequestTraceStatus,
  options: {
    readonly response?: Response;
    readonly teardown: StartRequestTraceTeardown;
    readonly stream?: StartRequestTraceStream;
  }
): StartRequestTrace => {
  const traceStatus = facts.failureKind === undefined || status === "cancelled"
    ? status
    : "failure";
  const fiberStatus: StartRequestTraceFiberStatus = traceStatus === "success"
    ? "done"
    : traceStatus === "cancelled" || facts.failureKind === "interruption"
      ? "interrupted"
      : "failed";

  return {
    request: traceRequest(request, facts),
    ...(options.response === undefined ? {} : { response: traceResponse(options.response) }),
    services: ["RequestContext", "ResponseContext"],
    ...(facts.routePlan === undefined ? {} : { routePlan: facts.routePlan }),
    resources: facts.routePlan?.resources ?? [],
    collections: facts.collections,
    serverFunctions: [...facts.serverFunctions],
    actions: [...facts.actions],
    fibers: [
      {
        name: "request-runtime",
        status: fiberStatus
      }
    ],
    streams: options.stream === undefined ? [] : [options.stream],
    status: traceStatus,
    ...(facts.failureKind === undefined ? {} : { failureKind: facts.failureKind }),
    teardown: options.teardown
  };
};

export const requestRuntimeTeardownSnapshot = <RuntimeServices, RuntimeError>(
  runtime: EffectUiRuntime<RuntimeServices, RuntimeError>
): StartRequestTraceTeardownSnapshot =>
  runtime.resourceStore.diagnostics.snapshotUnsafe();

export const requestRuntimeDisposeTraceEffect = <RuntimeServices, RuntimeError>(
  runtime: EffectUiRuntime<RuntimeServices, RuntimeError>
): Effect.Effect<{
  readonly beforeDispose: StartRequestTraceTeardownSnapshot;
  readonly afterDispose: StartRequestTraceTeardownSnapshot;
  readonly completedAt: number;
}> =>
  Effect.gen(function* () {
    const beforeDispose = requestRuntimeTeardownSnapshot(runtime);
    yield* runtime.disposeEffect;
    const afterDispose = requestRuntimeTeardownSnapshot(runtime);
    const completedAt = yield* Clock.currentTimeMillis;
    return {
      beforeDispose,
      afterDispose,
      completedAt
    };
  });

export const startRequestTraceTeardown = (
  facts: StartRequestTraceFacts,
  options: {
    readonly runtimeDisposed: boolean;
    readonly reason: string;
    readonly completedAt: number;
    readonly beforeDispose: StartRequestTraceTeardownSnapshot;
    readonly afterDispose: StartRequestTraceTeardownSnapshot;
  }
): StartRequestTraceTeardown => ({
  runtimeDisposed: options.runtimeDisposed,
  reason: options.reason,
  at: options.completedAt,
  startedAt: facts.startedAt,
  completedAt: options.completedAt,
  durationMillis: Math.max(0, options.completedAt - facts.startedAt),
  beforeDispose: options.beforeDispose,
  afterDispose: options.afterDispose
});
