// This file is generated by @effect-ui/start. Do not edit.

import type { Route } from "@effect-ui/core";

import { Route as route_root } from "./routes/index.js";
import { Route as route_projects } from "./routes/projects/index.js";
import { Route as route_projects_$id } from "./routes/projects/$id.js";

const route_root_path: "/" = route_root.path;
const route_projects_path: "/projects" = route_projects.path;
const route_projects_$id_path: "/projects/:id" = route_projects_$id.path;

export { route_root, route_projects, route_projects_$id };

export const routes = [route_root, route_projects, route_projects_$id] as const;
export const routeTree = routes;
export const routeById = {
  "route_root": route_root,
  "route_projects": route_projects,
  "route_projects_$id": route_projects_$id
} as const;
export const routeByPath = {
  "/": route_root,
  "/projects": route_projects,
  "/projects/:id": route_projects_$id
} as const;

export const fileRouteModules = [
  {
    "id": "index",
    "kind": "Route",
    "routeId": "route_root",
    "moduleId": "src/routes/index.ts",
    "filePath": "src/routes/index.ts",
    "routePath": "/",
    "segments": [],
    "params": [],
    "exportName": "Route"
  },
  {
    "id": "projects/index",
    "kind": "Route",
    "routeId": "route_projects",
    "moduleId": "src/routes/projects/index.ts",
    "filePath": "src/routes/projects/index.ts",
    "routePath": "/projects",
    "segments": [
      {
        "_tag": "Static",
        "value": "projects"
      }
    ],
    "params": [],
    "exportName": "Route"
  },
  {
    "id": "projects/$id",
    "kind": "Route",
    "routeId": "route_projects_$id",
    "moduleId": "src/routes/projects/$id.ts",
    "filePath": "src/routes/projects/$id.ts",
    "routePath": "/projects/:id",
    "segments": [
      {
        "_tag": "Static",
        "value": "projects"
      },
      {
        "_tag": "Dynamic",
        "name": "id",
        "optional": false
      }
    ],
    "params": [
      {
        "name": "id",
        "optional": false
      }
    ],
    "exportName": "Route"
  }
] as const;
export const fileRouteMetadata = [
  {
    "routeId": "route_root",
    "routePath": "/",
    "routeModule": {
      "id": "index",
      "kind": "Route",
      "routeId": "route_root",
      "moduleId": "src/routes/index.ts",
      "filePath": "src/routes/index.ts",
      "routePath": "/",
      "segments": [],
      "params": [],
      "exportName": "Route"
    },
    "layouts": [],
    "metadataModules": []
  },
  {
    "routeId": "route_projects",
    "routePath": "/projects",
    "routeModule": {
      "id": "projects/index",
      "kind": "Route",
      "routeId": "route_projects",
      "moduleId": "src/routes/projects/index.ts",
      "filePath": "src/routes/projects/index.ts",
      "routePath": "/projects",
      "segments": [
        {
          "_tag": "Static",
          "value": "projects"
        }
      ],
      "params": [],
      "exportName": "Route"
    },
    "parentRouteId": "route_root",
    "parentRoutePath": "/",
    "layouts": [],
    "metadataModules": []
  },
  {
    "routeId": "route_projects_$id",
    "routePath": "/projects/:id",
    "routeModule": {
      "id": "projects/$id",
      "kind": "Route",
      "routeId": "route_projects_$id",
      "moduleId": "src/routes/projects/$id.ts",
      "filePath": "src/routes/projects/$id.ts",
      "routePath": "/projects/:id",
      "segments": [
        {
          "_tag": "Static",
          "value": "projects"
        },
        {
          "_tag": "Dynamic",
          "name": "id",
          "optional": false
        }
      ],
      "params": [
        {
          "name": "id",
          "optional": false
        }
      ],
      "exportName": "Route"
    },
    "parentRouteId": "route_projects",
    "parentRoutePath": "/projects",
    "layouts": [],
    "metadataModules": []
  }
] as const;

export type RouteTree = typeof routeTree;
export type RouteById = typeof routeById;
export type RouteByPath = typeof routeByPath;
export type FileRoute = RouteTree[number];
export type FileRouteId = keyof RouteById;
export type FileRoutePath = keyof RouteByPath;
export type FileRouteByPath = RouteByPath;
export type FileRouteParamsById = { readonly [Id in FileRouteId]: Route.Params<RouteById[Id]> };
export type FileRouteSearchById = { readonly [Id in FileRouteId]: Route.Search<RouteById[Id]> };
export type FileRouteHrefOptionsById = { readonly [Id in FileRouteId]: Route.HrefOptions<RouteById[Id]> };
export type FileRouteHrefOptions<Id extends FileRouteId> = FileRouteHrefOptionsById[Id];
export type FileRouteParamsByPath = { readonly [Path in keyof FileRouteByPath]: Route.Params<FileRouteByPath[Path]> };
export type FileRouteSearchByPath = { readonly [Path in keyof FileRouteByPath]: Route.Search<FileRouteByPath[Path]> };
export type FileRouteHrefOptionsByPath = { readonly [Path in keyof FileRouteByPath]: Route.HrefOptions<FileRouteByPath[Path]> };
export type FileRouteModules = typeof fileRouteModules;
export type FileRouteMetadata = typeof fileRouteMetadata;
export default routes;
